export interface ComprehensiveItem {
  id: string;
  name: string;
  description: string;
  type: 'weapon' | 'shield' | 'armor' | 'mount' | 'potion' | 'scroll' | 'artifact' | 'material' | 'food';
  category: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  stats: {
    attack?: number;
    defense?: number;
    movement?: number;
    health?: number;
    mana?: number;
    stamina?: number;
    gold?: number;
    experience?: number;
  };
  emoji: string;
  image: string;
  cost: number;
  isDefault?: boolean;
  isEquippable: boolean;
  isConsumable: boolean;
}

export const comprehensiveItems: ComprehensiveItem[] = [
  // ==========================================
  // WEAPONS (SWORDS)
  // ==========================================
  {
    id: 'sword-twig',
    name: 'Twig Sword',
    description: 'A simple wooden sword - every adventurer starts somewhere',
    type: 'weapon',
    category: 'weapon',
    rarity: 'common',
    stats: { attack: 2 },
    emoji: '🗡️',
    image: '/images/items/sword/sword-twig.webp',
    cost: 25,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-irony',
    name: 'Iron Sword',
    description: 'A sturdy iron sword with good balance and durability',
    type: 'weapon',
    category: 'weapon',
    rarity: 'uncommon',
    stats: { attack: 5 },
    emoji: '⚔️',
    image: '/images/items/sword/sword-irony.webp',
    cost: 120,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-morningstar',
    name: 'Morningstar',
    description: 'A spiked mace that delivers devastating crushing blows',
    type: 'weapon',
    category: 'weapon',
    rarity: 'rare',
    stats: { attack: 8 },
    emoji: '🔨',
    image: '/images/items/sword/sword-morningstar.webp',
    cost: 250,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-sunblade',
    name: 'Sunblade',
    description: 'A radiant sword that glows with the power of the sun',
    type: 'weapon',
    category: 'weapon',
    rarity: 'epic',
    stats: { attack: 12, mana: 5 },
    emoji: '☀️',
    image: '/images/items/sword/sword-sunblade.webp',
    cost: 500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-solaraxe',
    name: 'Solar Axe',
    description: 'A mighty axe that channels the fury of the sun',
    type: 'weapon',
    category: 'weapon',
    rarity: 'legendary',
    stats: { attack: 18, health: 10 },
    emoji: '🪓',
    image: '/images/items/sword/sword-solaraxe.webp',
    cost: 1000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // SHIELDS
  // ==========================================
  {
    id: 'shield-reflecto',
    name: 'Reflecto Shield',
    description: 'A basic wooden shield - it may not look like much, but it gets the job done',
    type: 'shield',
    category: 'shield',
    rarity: 'common',
    stats: { defense: 2 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-reflecto.webp',
    cost: 30,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-defecto',
    name: 'Defecto Shield',
    description: 'A reinforced wooden shield with iron bands',
    type: 'shield',
    category: 'shield',
    rarity: 'uncommon',
    stats: { defense: 4 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-defecto.webp',
    cost: 80,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-blockado',
    name: 'Blockado Shield',
    description: 'A solid iron shield that blocks most attacks',
    type: 'shield',
    category: 'shield',
    rarity: 'rare',
    stats: { defense: 7 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-blockado.webp',
    cost: 200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-shellow',
    name: 'Shellow Shield',
    description: 'A magical shield that absorbs and reflects damage',
    type: 'shield',
    category: 'shield',
    rarity: 'epic',
    stats: { defense: 10, health: 5 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-shellow.webp',
    cost: 400,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-shielow',
    name: 'Shielow Shield',
    description: 'A legendary shield that grants divine protection',
    type: 'shield',
    category: 'shield',
    rarity: 'legendary',
    stats: { defense: 15, health: 10, mana: 5 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-shielow.webp',
    cost: 800,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // ARMOR
  // ==========================================
  {
    id: 'armor-normalo',
    name: 'Normalo Armor',
    description: 'Standard issue armor for new adventurers',
    type: 'armor',
    category: 'armor',
    rarity: 'common',
    stats: { defense: 1 },
    emoji: '🥋',
    image: '/images/items/armor/armor-normalo.webp',
    cost: 50,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-darko',
    name: 'Darko Armor',
    description: 'Dark leather armor that provides stealth and protection',
    type: 'armor',
    category: 'armor',
    rarity: 'uncommon',
    stats: { defense: 3, health: 2 },
    emoji: '🥋',
    image: '/images/items/armor/armor-darko.webp',
    cost: 150,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-blanko',
    name: 'Blanko Armor',
    description: 'A blank canvas armor that can be enchanted',
    type: 'armor',
    category: 'armor',
    rarity: 'rare',
    stats: { defense: 5 },
    emoji: '🥋',
    image: '/images/items/armor/armor-blanko.webp',
    cost: 300,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-silvo',
    name: 'Silvo Armor',
    description: 'Silvery armor that gleams with magical properties',
    type: 'armor',
    category: 'armor',
    rarity: 'epic',
    stats: { defense: 8, mana: 3 },
    emoji: '🥋',
    image: '/images/items/armor/armor-silvo.webp',
    cost: 600,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-goldo',
    name: 'Goldo Armor',
    description: 'Golden armor that radiates with divine power',
    type: 'armor',
    category: 'armor',
    rarity: 'legendary',
    stats: { defense: 12, health: 8, mana: 5 },
    emoji: '🥋',
    image: '/images/items/armor/armor-goldo.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // MOUNTS (HORSES)
  // ==========================================
  {
    id: 'horse-stelony',
    name: 'Stelony',
    description: 'A sturdy pony with basic armor - your trusty starter mount',
    type: 'mount',
    category: 'mount',
    rarity: 'common',
    stats: { movement: 5 },
    emoji: '🐎',
    image: '/images/items/horse/horse-stelony.webp',
    cost: 100,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-perony',
    name: 'Perony',
    description: 'A swift horse bred for speed and endurance',
    type: 'mount',
    category: 'mount',
    rarity: 'uncommon',
    stats: { movement: 8 },
    emoji: '🐎',
    image: '/images/items/horse/horse-perony.webp',
    cost: 250,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-felony',
    name: 'Felony',
    description: 'A fierce war horse trained for battle',
    type: 'mount',
    category: 'mount',
    rarity: 'rare',
    stats: { movement: 6, attack: 3 },
    emoji: '🐎',
    image: '/images/items/horse/horse-felony.webp',
    cost: 500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-goldy',
    name: 'Goldy',
    description: 'A golden horse with magical properties',
    type: 'mount',
    category: 'mount',
    rarity: 'epic',
    stats: { movement: 10, mana: 5 },
    emoji: '🐎',
    image: '/images/items/horse/horse-goldy.webp',
    cost: 800,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-silvy',
    name: 'Silvy',
    description: 'A legendary silver horse that can fly',
    type: 'mount',
    category: 'mount',
    rarity: 'legendary',
    stats: { movement: 15, health: 10, mana: 8 },
    emoji: '🐎',
    image: '/images/items/horse/horse-silvy.webp',
    cost: 1500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // POTIONS
  // ==========================================
  {
    id: 'potion-health',
    name: 'Health Potion',
    description: 'Restores health and vitality',
    type: 'potion',
    category: 'item',
    rarity: 'common',
    stats: { health: 50 },
    emoji: '❤️',
    image: '/images/items/potion/potion-health.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-mana',
    name: 'Mana Potion',
    description: 'Restores magical energy',
    type: 'potion',
    category: 'item',
    rarity: 'common',
    stats: { mana: 50 },
    emoji: '🌀',
    image: '/images/items/potion/potion-mana.webp',
    cost: 30,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-stamina',
    name: 'Stamina Potion',
    description: 'Boosts endurance and movement',
    type: 'potion',
    category: 'item',
    rarity: 'uncommon',
    stats: { stamina: 75 },
    emoji: '💪',
    image: '/images/items/potion/potion-stamina.webp',
    cost: 40,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-exp',
    name: 'Experience Potion',
    description: 'Grants bonus experience points',
    type: 'potion',
    category: 'item',
    rarity: 'rare',
    stats: { experience: 100 },
    emoji: '⭐',
    image: '/images/items/potion/potion-exp.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-gold',
    name: 'Gold Potion',
    description: 'Increases gold drops temporarily',
    type: 'potion',
    category: 'item',
    rarity: 'epic',
    stats: { gold: 200 },
    emoji: '🪙',
    image: '/images/items/potion/potion-gold.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // SCROLLS
  // ==========================================
  {
    id: 'scroll-scrolly',
    name: 'Scroll of Scrolly',
    description: 'A basic magical scroll with simple spells',
    type: 'scroll',
    category: 'scroll',
    rarity: 'common',
    stats: { mana: 20 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-scrolly.webp',
    cost: 50,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-memento',
    name: 'Scroll of Memory',
    description: 'Enhances memory and learning abilities',
    type: 'scroll',
    category: 'scroll',
    rarity: 'uncommon',
    stats: { experience: 50, mana: 30 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-memento.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-perkamento',
    name: 'Scroll of Perkament',
    description: 'Grants temporary skill bonuses',
    type: 'scroll',
    category: 'scroll',
    rarity: 'rare',
    stats: { attack: 5, defense: 5, mana: 40 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-perkamento.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-diamono',
    name: 'Scroll of Diamono',
    description: 'A precious scroll that enhances all attributes',
    type: 'scroll',
    category: 'scroll',
    rarity: 'epic',
    stats: { attack: 8, defense: 8, health: 50, mana: 60 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-diamono.webp',
    cost: 400,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-observio',
    name: 'Scroll of Observio',
    description: 'Reveals hidden secrets and treasures',
    type: 'scroll',
    category: 'scroll',
    rarity: 'legendary',
    stats: { mana: 100, experience: 200 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-observio.webp',
    cost: 800,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // ARTIFACTS
  // ==========================================
  {
    id: 'artifact-ringo',
    name: 'Ring of Power',
    description: 'A magical ring that enhances magical abilities',
    type: 'artifact',
    category: 'equipment',
    rarity: 'rare',
    stats: { mana: 30, health: 20 },
    emoji: '💍',
    image: '/images/items/artifact/ring/artifact-ringo.webp',
    cost: 500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-crowny',
    name: 'Royal Crown',
    description: 'A crown that grants leadership and charisma',
    type: 'artifact',
    category: 'equipment',
    rarity: 'epic',
    stats: { health: 50, mana: 40, defense: 5 },
    emoji: '👑',
    image: '/images/items/artifact/crown/artifact-crowny.webp',
    cost: 1000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-staffy',
    name: 'Staff of Wisdom',
    description: 'A staff that channels ancient knowledge',
    type: 'artifact',
    category: 'equipment',
    rarity: 'epic',
    stats: { mana: 60, attack: 8 },
    emoji: '🪄',
    image: '/images/items/artifact/scepter/artifact-staffy.webp',
    cost: 800,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-throny',
    name: 'Throne of Authority',
    description: 'A throne that grants dominion over realms',
    type: 'artifact',
    category: 'equipment',
    rarity: 'legendary',
    stats: { health: 100, mana: 80, defense: 10, attack: 10 },
    emoji: '🪑',
    image: '/images/items/artifact/throne/artifact-throny.webp',
    cost: 2000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-ropy',
    name: 'Robe of the Archmage',
    description: 'A robe that enhances magical prowess',
    type: 'artifact',
    category: 'equipment',
    rarity: 'epic',
    stats: { mana: 70, defense: 8, health: 30 },
    emoji: '👘',
    image: '/images/items/artifact/robe/artifact-ropy.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // MATERIALS
  // ==========================================
  {
    id: 'material-logs',
    name: 'Wooden Logs',
    description: 'Basic building material for construction',
    type: 'material',
    category: 'resource',
    rarity: 'common',
    stats: {},
    emoji: '🪵',
    image: '/images/items/materials/material-logs.webp',
    cost: 10,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-planks',
    name: 'Wooden Planks',
    description: 'Refined wood planks for advanced construction',
    type: 'material',
    category: 'resource',
    rarity: 'uncommon',
    stats: {},
    emoji: '🪵',
    image: '/images/items/materials/material-planks.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-steel',
    name: 'Steel Ingots',
    description: 'Strong metal for weapons and armor crafting',
    type: 'material',
    category: 'resource',
    rarity: 'rare',
    stats: {},
    emoji: '⚔️',
    image: '/images/items/materials/material-steel.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-silver',
    name: 'Silver Bars',
    description: 'Precious metal for magical items and advanced crafting',
    type: 'material',
    category: 'resource',
    rarity: 'epic',
    stats: {},
    emoji: '✨',
    image: '/images/items/materials/material-silver.webp',
    cost: 250,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-gold',
    name: 'Gold Bars',
    description: 'Legendary material for the most powerful items',
    type: 'material',
    category: 'resource',
    rarity: 'legendary',
    stats: {},
    emoji: '👑',
    image: '/images/items/materials/material-gold.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-crystal',
    name: 'Essence Crystal',
    description: 'A glowing crystal pulsing with magical energy',
    type: 'material',
    category: 'resource',
    rarity: 'rare',
    stats: {},
    emoji: '💎',
    image: '/images/items/materials/material-crystal.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // FOOD
  // ==========================================
  {
    id: 'food-red',
    name: 'Red Fish',
    description: 'A vibrant red fish that provides basic nourishment',
    type: 'food',
    category: 'resource',
    rarity: 'common',
    stats: { health: 15, stamina: 10 },
    emoji: '🐟',
    image: '/images/items/food/fish-red.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-blue',
    name: 'Blue Fish',
    description: 'A cool blue fish that refreshes and energizes',
    type: 'food',
    category: 'resource',
    rarity: 'uncommon',
    stats: { health: 20, stamina: 15, mana: 5 },
    emoji: '🐟',
    image: '/images/items/food/fish-blue.webp',
    cost: 40,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-silver',
    name: 'Silver Fish',
    description: 'A shimmering silver fish that enhances vitality',
    type: 'food',
    category: 'resource',
    rarity: 'rare',
    stats: { health: 25, stamina: 20, defense: 2 },
    emoji: '🐟',
    image: '/images/items/food/fish-silver.webp',
    cost: 60,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-golden',
    name: 'Golden Fish',
    description: 'A rare golden fish that provides nourishment and luck',
    type: 'food',
    category: 'resource',
    rarity: 'epic',
    stats: { health: 35, stamina: 25, mana: 10 },
    emoji: '🐟',
    image: '/images/items/food/fish-golden.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-rainbow',
    name: 'Rainbow Fish',
    description: 'A magical rainbow fish that grants multiple benefits',
    type: 'food',
    category: 'resource',
    rarity: 'legendary',
    stats: { health: 50, stamina: 35, mana: 20, attack: 5 },
    emoji: '🐟',
    image: '/images/items/food/fish-rainbow.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
];

// Helper functions
export const getItemById = (id: string): ComprehensiveItem | undefined => {
  return comprehensiveItems.find(item => item.id === id);
};

export const getItemsByType = (type: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.type === type);
};

export const getItemsByCategory = (category: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.category === category);
};

export const getItemsByRarity = (rarity: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.rarity === rarity);
};

export const getEquippableItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isEquippable);
};

export const getConsumableItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isConsumable);
};

export const getDefaultItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isDefault);
};
