export interface ComprehensiveItem {
  id: string;
  name: string;
  description: string;
  type: 'weapon' | 'shield' | 'armor' | 'robes' | 'robe' | 'footwear' | 'mount' | 'potion' | 'scroll' | 'artifact' | 'material' | 'food' | 'consumable' | 'building' | 'siege_engine' | 'tool' | 'shelter' | 'reagent' | 'currency' | 'key';
  category: 'weapon' | 'shield' | 'armor' | 'robes' | 'robe' | 'footwear' | 'mount' | 'consumable' | 'scroll' | 'artifact' | 'material' | 'building' | 'siege_engine';
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  stats: {
    attack?: number;
    defense?: number;
    movement?: number;
    health?: number;
    mana?: number;
    stamina?: number;
    gold?: number;
    experience?: number;
  };
  emoji: string;
  image: string;
  cost: number;
  isDefault?: boolean;
  isEquippable: boolean;
  isConsumable: boolean;
}

export const comprehensiveItems: ComprehensiveItem[] = [
  // ==========================================
  // WEAPONS (SWORDS)
  // ==========================================
  {
    id: 'sword-twig',
    name: 'Twig Sword',
    description: 'A simple wooden sword - every adventurer starts somewhere',
    type: 'weapon',
    category: 'weapon',
    rarity: 'common',
    stats: { attack: 3, movement: 1 },
    emoji: '🗡️',
    image: '/images/items/sword/sword-twig.webp',
    cost: 75,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-irony',
    name: 'Iron Sword',
    description: 'A sturdy iron sword with good balance and durability',
    type: 'weapon',
    category: 'weapon',
    rarity: 'uncommon',
    stats: { attack: 6, defense: 1 },
    emoji: '⚔️',
    image: '/images/items/sword/sword-irony.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-morningstar',
    name: 'Morningstar',
    description: 'A spiked mace that delivers devastating crushing blows',
    type: 'weapon',
    category: 'weapon',
    rarity: 'rare',
    stats: { attack: 9, defense: 2 },
    emoji: '🔨',
    image: '/images/items/sword/sword-morningstar.webp',
    cost: 8500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-sunblade',
    name: 'Sunblade',
    description: 'A radiant sword that glows with the power of the sun',
    type: 'weapon',
    category: 'weapon',
    rarity: 'epic',
    stats: { attack: 14, defense: 2, mana: 5 },
    emoji: '☀️',
    image: '/images/items/sword/sword-sunblade.webp',
    cost: 50000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-solaraxe',
    name: 'Solar Axe',
    description: 'A mighty axe that channels the fury of the sun',
    type: 'weapon',
    category: 'weapon',
    rarity: 'legendary',
    stats: { attack: 20, defense: 4, health: 15 },
    emoji: '🪓',
    image: '/images/items/sword/sword-solaraxe.webp',
    cost: 250000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // SHIELDS
  // ==========================================
  {
    id: 'shield-reflecto',
    name: 'Reflecto Shield',
    description: 'A basic wooden shield - it may not look like much, but it gets the job done',
    type: 'shield',
    category: 'shield',
    rarity: 'common',
    stats: { defense: 3, health: 5 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-reflecto.webp',
    cost: 75,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-defecto',
    name: 'Defecto Shield',
    description: 'A reinforced wooden shield with iron bands',
    type: 'shield',
    category: 'shield',
    rarity: 'uncommon',
    stats: { defense: 6, health: 8 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-defecto.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-blockado',
    name: 'Blockado Shield',
    description: 'A solid iron shield that blocks most attacks',
    type: 'shield',
    category: 'shield',
    rarity: 'rare',
    stats: { defense: 9, health: 12, attack: 1 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-blockado.webp',
    cost: 8500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-shellow',
    name: 'Shellow Shield',
    description: 'A magical shield that absorbs and reflects damage',
    type: 'shield',
    category: 'shield',
    rarity: 'epic',
    stats: { defense: 13, health: 18, attack: 2 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-shellow.webp',
    cost: 45000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-shielow',
    name: 'Shielow Shield',
    description: 'A legendary shield that grants divine protection',
    type: 'shield',
    category: 'shield',
    rarity: 'legendary',
    stats: { defense: 18, health: 25, mana: 8, attack: 4 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-shielow.webp',
    cost: 200000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // ARMOR
  // ==========================================
  {
    id: 'armor-normalo',
    name: 'Normalo Armor',
    description: 'Standard issue armor for new adventurers',
    type: 'armor',
    category: 'armor',
    rarity: 'common',
    stats: { defense: 4, health: 5 },
    emoji: '🥋',
    image: '/images/items/armor/armor-normalo.webp',
    cost: 100,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-darko',
    name: 'Darko Armor',
    description: 'Dark leather armor that provides stealth and protection',
    type: 'armor',
    category: 'armor',
    rarity: 'uncommon',
    stats: { defense: 7, movement: 3, health: 8 },
    emoji: '🥋',
    image: '/images/items/armor/armor-darko.webp',
    cost: 1500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-blanko',
    name: 'Blanko Armor',
    description: 'A blank canvas armor that can be enchanted',
    type: 'armor',
    category: 'armor',
    rarity: 'rare',
    stats: { defense: 10, attack: 2, health: 12 },
    emoji: '🥋',
    image: '/images/items/armor/armor-blanko.webp',
    cost: 10000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-silvo',
    name: 'Silvo Armor',
    description: 'Silvery armor that gleams with magical properties',
    type: 'armor',
    category: 'armor',
    rarity: 'epic',
    stats: { defense: 14, mana: 6, movement: 2, health: 15 },
    emoji: '🥋',
    image: '/images/items/armor/armor-silvo.webp',
    cost: 55000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-goldo',
    name: 'Goldo Armor',
    description: 'Golden armor that radiates with divine power',
    type: 'armor',
    category: 'armor',
    rarity: 'legendary',
    stats: { defense: 20, health: 25, mana: 10, attack: 4 },
    emoji: '🥋',
    image: '/images/items/armor/armor-goldo.webp',
    cost: 280000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // MOUNTS (HORSES)
  // ==========================================
  {
    id: 'horse-stelony',
    name: 'Stelony',
    description: 'A sturdy pony with basic armor - your trusty starter mount',
    type: 'mount',
    category: 'mount',
    rarity: 'common',
    stats: { movement: 6, defense: 2 },
    emoji: '🐎',
    image: '/images/items/horse/horse-stelony.webp',
    cost: 150,
    isDefault: true,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-perony',
    name: 'Perony',
    description: 'A swift horse bred for speed and endurance',
    type: 'mount',
    category: 'mount',
    rarity: 'uncommon',
    stats: { movement: 9, defense: 3, attack: 1 },
    emoji: '🐎',
    image: '/images/items/horse/horse-perony.webp',
    cost: 2500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-felony',
    name: 'Felony',
    description: 'A fierce war horse trained for battle',
    type: 'mount',
    category: 'mount',
    rarity: 'rare',
    stats: { movement: 8, attack: 6, defense: 4 },
    emoji: '🐎',
    image: '/images/items/horse/horse-felony.webp',
    cost: 15000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-goldy',
    name: 'Goldy',
    description: 'A golden horse with magical properties',
    type: 'mount',
    category: 'mount',
    rarity: 'epic',
    stats: { movement: 12, defense: 5, mana: 8, attack: 3 },
    emoji: '🐎',
    image: '/images/items/horse/horse-goldy.webp',
    cost: 75000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'horse-silvy',
    name: 'Silvy',
    description: 'A legendary silver horse that can fly',
    type: 'mount',
    category: 'mount',
    rarity: 'legendary',
    stats: { movement: 18, health: 20, mana: 10, attack: 6, defense: 6 },
    emoji: '🐎',
    image: '/images/items/horse/horse-silvy.webp',
    cost: 350000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // POTIONS
  // ==========================================
  {
    id: 'potion-health',
    name: 'Health potion',
    description: 'Restores health and vitality',
    type: 'potion',
    category: 'consumable',
    rarity: 'common',
    stats: { health: 50 },
    emoji: '❤️',
    image: '/images/items/potion/potion-health.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-mana',
    name: 'Mana potion',
    description: 'Restores magical energy',
    type: 'potion',
    category: 'consumable',
    rarity: 'common',
    stats: { mana: 50 },
    emoji: '🌀',
    image: '/images/items/potion/potion-mana.webp',
    cost: 30,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-stamina',
    name: 'Stamina potion',
    description: 'Boosts endurance and movement',
    type: 'potion',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { stamina: 75 },
    emoji: '💪',
    image: '/images/items/potion/potion-stamina.webp',
    cost: 40,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-exp',
    name: 'Exp potion',
    description: 'Grants bonus experience points',
    type: 'potion',
    category: 'consumable',
    rarity: 'rare',
    stats: { experience: 100 },
    emoji: '⭐',
    image: '/images/items/potion/potion-exp.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-gold',
    name: 'Gold potion',
    description: 'Increases gold drops temporarily',
    type: 'potion',
    category: 'consumable',
    rarity: 'epic',
    stats: { gold: 200 },
    emoji: '🪙',
    image: '/images/items/potion/potion-gold.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-forge-luck',
    name: 'Forge luck elixir',
    description: 'Increases Blacksmith Tempering success rate by +10% for your next upgrade attempt',
    type: 'potion',
    category: 'consumable',
    rarity: 'rare',
    stats: {},
    emoji: '🧪',
    image: '/images/items/potion/potion-forge-luck.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-combat-protection',
    name: 'Protection',
    description: 'Prevents gold loss on round failures in your next Monster Battle',
    type: 'potion',
    category: 'consumable',
    rarity: 'epic',
    stats: {},
    emoji: '🧪',
    image: '/images/items/potion/potion-combat-protection.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-double-harvest',
    name: 'Double Harvest Draught',
    description: 'Nourishes citizens, giving them +100% harvesting item yields on their next collection',
    type: 'potion',
    category: 'consumable',
    rarity: 'uncommon',
    stats: {},
    emoji: '🧪',
    image: '/images/items/potion/potion-double-harvest.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-greek-fire',
    name: 'Greek Fire Oil',
    description: 'Applied before Titan Wyrm raids to deal +25% burning siege damage over 3 turns',
    type: 'potion',
    category: 'consumable',
    rarity: 'rare',
    stats: { attack: 15 },
    emoji: '🔥',
    image: '/images/items/potion/potion-greek-fire.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-dragonblood',
    name: 'Dragonblood Tincture',
    description: 'Tincture that grants +20% Critical Strike Chance in 3v3 Dungeon Keep battles',
    type: 'potion',
    category: 'consumable',
    rarity: 'rare',
    stats: { attack: 20 },
    emoji: '🛡️',
    image: '/images/items/potion/potion-dragonblood.webp',
    cost: 175,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-golden-nectar',
    name: 'Golden Nectar Treat',
    description: 'Fed to Guardian Pets in Vault to gain +10% Affection and double passive daily resource yields',
    type: 'potion',
    category: 'consumable',
    rarity: 'epic',
    stats: { stamina: 50 },
    emoji: '🍯',
    image: '/images/items/potion/potion-golden-nectar.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'golden_apple',
    name: 'Golden apple',
    description: 'A rare botanical delicacy harvested from fertile vegetable gardens. Fed to guardian pets to raise affection by +5% and strengthen passive kingdom yields',
    type: 'material',
    category: 'consumable',
    rarity: 'rare',
    stats: { stamina: 25 },
    emoji: '🍎',
    image: '/images/items/materials/material-apple.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-stormbreaker',
    name: 'Stormbreaker Tonic',
    description: 'Consumed during Airship voyages to shield crew and cargo from Ether storm hazards',
    type: 'potion',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { movement: 10 },
    emoji: '🌩️',
    image: '/images/items/potion/potion-stormbreaker.webp',
    cost: 120,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'potion-honor-elixir',
    name: 'Elixir of Honor',
    description: 'Drunk during 1v1 Virtue Duels / House Cup to award +10 bonus virtue points to both allies',
    type: 'potion',
    category: 'consumable',
    rarity: 'epic',
    stats: { mana: 40 },
    emoji: '⚖️',
    image: '/images/items/potion/potion-honor-elixir.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // SCROLLS
  // ==========================================
  {
    id: 'scroll-scrolly',
    name: 'Scroll of Scrolly',
    description: 'A basic magical scroll with simple spells',
    type: 'scroll',
    category: 'scroll',
    rarity: 'common',
    stats: { mana: 20 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-scrolly.webp',
    cost: 50,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-memento',
    name: 'Scroll of Memory',
    description: 'Enhances memory and learning abilities',
    type: 'scroll',
    category: 'scroll',
    rarity: 'uncommon',
    stats: { experience: 50, mana: 30 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-memento.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-perkamento',
    name: 'Scroll of Perkament',
    description: 'Grants temporary skill bonuses',
    type: 'scroll',
    category: 'scroll',
    rarity: 'rare',
    stats: { attack: 5, defense: 5, mana: 40 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-perkamento.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-diamono',
    name: 'Scroll of Diamono',
    description: 'A precious scroll that enhances all attributes',
    type: 'scroll',
    category: 'scroll',
    rarity: 'epic',
    stats: { attack: 8, defense: 8, health: 50, mana: 60 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-diamono.webp',
    cost: 400,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-observio',
    name: 'Scroll of Observio',
    description: 'Reveals hidden secrets and treasures',
    type: 'scroll',
    category: 'scroll',
    rarity: 'legendary',
    stats: { mana: 100, experience: 200 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-observio.webp',
    cost: 800,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // ARTIFACTS
  // ==========================================
  {
    id: 'artifact-ringo',
    name: 'Ring of Power',
    description: 'A magical ring that enhances magical abilities',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { mana: 30, health: 20 },
    emoji: '💍',
    image: '/images/items/artifact/ring/artifact-ringo.webp',
    cost: 12000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-crowny',
    name: 'Royal Crown',
    description: 'A crown that grants leadership and charisma',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { health: 50, mana: 40, defense: 5 },
    emoji: '👑',
    image: '/images/items/artifact/crown/artifact-crowny.webp',
    cost: 80000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-staffy',
    name: 'Staff of Wisdom',
    description: 'A staff that channels ancient knowledge',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { mana: 60, attack: 8 },
    emoji: '🪄',
    image: '/images/items/artifact/scepter/artifact-staffy.webp',
    cost: 65000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-throny',
    name: 'Throne of Authority',
    description: 'A throne that grants dominion over realms',
    type: 'artifact',
    category: 'artifact',
    rarity: 'legendary',
    stats: { health: 100, mana: 80, defense: 10, attack: 10 },
    emoji: '🪑',
    image: '/images/items/artifact/throne/artifact-throny.webp',
    cost: 350000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-ropy',
    name: 'Robe of the archmage',
    description: 'A robe that enhances magical prowess and channels deep arcane habit focus.',
    type: 'robe',
    category: 'robe',
    rarity: 'epic',
    stats: { attack: 12, defense: 8, mana: 70, health: 30 },
    emoji: '👘',
    image: '/images/items/robe/artifact-ropy.webp',
    cost: 65000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'robe-apprentice',
    name: 'Apprentice robe',
    description: 'A simple spun-wool vestment worn by young acolytes learning their first cantrips.',
    type: 'robe',
    category: 'robe',
    rarity: 'common',
    stats: { mana: 15, defense: 2 },
    emoji: '🧙',
    image: '/images/items/robe/robe-apprentice.webp',
    cost: 150,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'robe-ranger-cloak',
    name: 'Ranger cloak',
    description: 'A forest-green hooded cloak that blends into wilderness foliage and keeps off the rain.',
    type: 'robe',
    category: 'robe',
    rarity: 'uncommon',
    stats: { movement: 6, attack: 4, defense: 4 },
    emoji: '🧥',
    image: '/images/items/robe/robe-ranger-cloak.webp',
    cost: 1400,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'robe-shadow-cowl',
    name: 'Shadow mantle',
    description: 'A dark silk mantle woven with twilight threads that conceals dungeon presence.',
    type: 'robe',
    category: 'robe',
    rarity: 'rare',
    stats: { movement: 10, attack: 8, defense: 6 },
    emoji: '🥷',
    image: '/images/items/robe/robe-shadow-cowl.webp',
    cost: 9500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'robe-archmage',
    name: 'Archmage vestment',
    description: 'An intricately embroidered robe saturated with concentrated elemental mana.',
    type: 'robe',
    category: 'robe',
    rarity: 'epic',
    stats: { attack: 15, defense: 10, mana: 80 },
    emoji: '🔮',
    image: '/images/items/robe/robe-archmage.webp',
    cost: 55000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'robe-celestial',
    name: 'Celestial mantle',
    description: 'A divine garment shimmering with starfire, worn by grand paragons of the realm.',
    type: 'robe',
    category: 'robe',
    rarity: 'legendary',
    stats: { attack: 18, defense: 18, mana: 120, health: 60 },
    emoji: '🌌',
    image: '/images/items/robe/robe-celestial.webp',
    cost: 220000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // ==========================================
  // MATERIALS
  // ==========================================
  {
    id: 'material-logs',
    name: 'Wooden Logs',
    description: 'Basic building material for construction',
    type: 'material',
    category: 'material',
    rarity: 'common',
    stats: {},
    emoji: '🪵',
    image: '/images/items/materials/material-logs.webp',
    cost: 10,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-planks',
    name: 'Wooden Planks',
    description: 'Refined wood planks for advanced construction',
    type: 'material',
    category: 'material',
    rarity: 'uncommon',
    stats: {},
    emoji: '🪵',
    image: '/images/items/materials/material-planks.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-steel',
    name: 'Steel Ingots',
    description: 'Strong metal for weapons and armor crafting',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: {},
    emoji: '⚔️',
    image: '/images/items/materials/material-steel.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-silver',
    name: 'Silver Bars',
    description: 'Precious metal for magical items and advanced crafting',
    type: 'material',
    category: 'material',
    rarity: 'epic',
    stats: {},
    emoji: '✨',
    image: '/images/items/materials/material-silver.webp',
    cost: 250,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-gold',
    name: 'Gold Bars',
    description: 'Legendary material for the most powerful items',
    type: 'material',
    category: 'material',
    rarity: 'legendary',
    stats: {},
    emoji: '👑',
    image: '/images/items/materials/material-gold.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-crystal',
    name: 'Essence Crystal',
    description: 'A glowing crystal pulsing with magical energy',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: {},
    emoji: '💎',
    image: '/images/items/materials/material-crystal.webp',
    cost: 150,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-stone',
    name: 'Cobblestone',
    description: 'A smooth, heavy stone. Good for building and brewing structures.',
    type: 'material',
    category: 'material',
    rarity: 'common',
    stats: {},
    emoji: '🪨',
    image: '/images/items/materials/material-stone.webp',
    cost: 5,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // ==========================================
  // FOOD
  // ==========================================
  {
    id: 'fish-red',
    name: 'Red Fish',
    description: 'A vibrant red fish that provides basic nourishment',
    type: 'consumable',
    category: 'consumable',
    rarity: 'common',
    stats: { health: 15, stamina: 10 },
    emoji: '🐟',
    image: '/images/items/food/fish-red.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'fish-blue',
    name: 'Blue Fish',
    description: 'A cool blue fish that refreshes and energizes',
    type: 'consumable',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { health: 20, stamina: 15, mana: 5 },
    emoji: '🐟',
    image: '/images/items/food/fish-blue.webp',
    cost: 40,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'fish-silver',
    name: 'Silver Fish',
    description: 'A shimmering silver fish that enhances vitality',
    type: 'consumable',
    category: 'consumable',
    rarity: 'rare',
    stats: { health: 25, stamina: 20, defense: 2 },
    emoji: '🐟',
    image: '/images/items/food/fish-silver.webp',
    cost: 60,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'fish-golden',
    name: 'Golden Fish',
    description: 'A rare golden fish that provides nourishment and luck',
    type: 'consumable',
    category: 'consumable',
    rarity: 'epic',
    stats: { health: 35, stamina: 25, mana: 10 },
    emoji: '🐟',
    image: '/images/items/food/fish-golden.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'fish-rainbow',
    name: 'Rainbow Fish',
    description: 'A magical rainbow fish that grants multiple benefits',
    type: 'consumable',
    category: 'consumable',
    rarity: 'legendary',
    stats: { health: 50, stamina: 35, mana: 20, attack: 5 },
    emoji: '🐟',
    image: '/images/items/food/fish-rainbow.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-water',
    name: 'Water',
    description: 'Fresh water drawn from a well. Essential for life.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'common',
    stats: { stamina: 10, health: 5 },
    emoji: '💧',
    image: '/images/items/materials/material-water.webp',
    cost: 5,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'prison',
    name: 'Iron Citadel Prison',
    description: 'A fortified dungeon tile for inmate trials and outlaw dilemmas',
    type: 'building',
    category: 'building',
    rarity: 'rare',
    stats: {},
    emoji: '🏰',
    image: '/images/tiles/prison-tile.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'apotheca',
    name: 'Grand Apotheca',
    description: 'A botanical glasshouse tile for daily mystery decoctions and trades',
    type: 'building',
    category: 'building',
    rarity: 'rare',
    stats: {},
    emoji: '🧪',
    image: '/images/tiles/apotheca-tile.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'waterway_canal',
    name: 'Waterway canal',
    description: 'A serene medieval canal tile with flowing aquamarine waters and arched stone bridge',
    type: 'building',
    category: 'building',
    rarity: 'epic',
    stats: { experience: 50 },
    emoji: '🌉',
    image: '/images/kingdom-tiles/WaterwayCanal.webp',
    cost: 750,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'astral_citadel_monument',
    name: 'Astral Citadel Monument',
    description: 'A colossal high-tier monument crowned with a glowing floating purple crystal orb',
    type: 'building',
    category: 'building',
    rarity: 'legendary',
    stats: { experience: 150, gold: 50 },
    emoji: '🔮',
    image: '/images/kingdom-tiles/AstralCitadelMonument.webp',
    cost: 1500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'serene_lake',
    name: 'Serene Lake',
    description: 'A tranquil aquamarine lake tile with pure shimmering water ripples',
    type: 'building',
    category: 'building',
    rarity: 'common',
    stats: { experience: 10 },
    emoji: '🌊',
    image: '/images/kingdom-tiles/SereneLake.webp',
    cost: 25,
    isDefault: true,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_catapult',
    name: 'Catapult',
    description: 'Unlocked at 100 Might Quests! Deployable on walkable Realm tiles for +20% Might & Fire Siege damage.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 20 },
    emoji: '🗡️',
    image: '/images/kingdom-tiles/siege_catapult.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_scorpion',
    name: 'Scorpion',
    description: 'Unlocked at 100 Knowledge Quests! Deployable on walkable Realm tiles for +20% Precision Siege damage.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 20 },
    emoji: '🧠',
    image: '/images/kingdom-tiles/siege_scorpion.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_battering_ram',
    name: 'Battering ram',
    description: 'Unlocked at 100 Honor Quests! Deployable on walkable Realm tiles for +20% Armor Break.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 20 },
    emoji: '🛡️',
    image: '/images/kingdom-tiles/siege_battering_ram.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_trebuchet',
    name: 'Trebuchet',
    description: 'Unlocked at 100 Vitality Quests! Deployable on walkable Realm tiles for +25% Heavy Siege Splash damage.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 25 },
    emoji: '❤️',
    image: '/images/kingdom-tiles/siege_trebuchet.webp',
    cost: 600,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_tower',
    name: 'Siegetower',
    description: 'Unlocked at 100 Castle Quests! Deployable on walkable Realm tiles for +20% Fortification Breach.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { defense: 20 },
    emoji: '🏰',
    image: '/images/kingdom-tiles/siege_tower.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_flame_ballista',
    name: 'Balista',
    description: 'Unlocked at 100 Craft Quests! Deployable on walkable Realm tiles for +20% Burning Bolt damage.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 20 },
    emoji: '🔧',
    image: '/images/kingdom-tiles/siege_flame_ballista.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_spring_cannon',
    name: 'Canon',
    description: 'Unlocked at 100 Wellness Quests! Deployable on walkable Realm tiles for +20% Squad Healing.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { stamina: 20 },
    emoji: '🌿',
    image: '/images/kingdom-tiles/siege_spring_cannon.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_ether_mortar',
    name: 'Flaming catapult',
    description: 'Unlocked at 100 Exploration Quests! Deployable on walkable Realm tiles for +20% Ether Bombardment.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 20 },
    emoji: '🧭',
    image: '/images/kingdom-tiles/siege_ether_mortar.webp',
    cost: 500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_dragon_mortar',
    name: 'Flaming scorpion',
    description: 'Unlocked at 100 Conquest Quests! Deployable on walkable Realm tiles for +25% Fire Blast damage.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 25 },
    emoji: '⚔️',
    image: '/images/kingdom-tiles/siege_dragon_mortar.webp',
    cost: 600,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'siege_astral_projector',
    name: 'Flaming trebuchet',
    description: 'Unlocked at 100 Spirit Quests! Deployable on walkable Realm tiles for +25% Holy Energy Surge.',
    type: 'siege_engine',
    category: 'siege_engine',
    rarity: 'legendary',
    stats: { attack: 25 },
    emoji: '✨',
    image: '/images/kingdom-tiles/siege_astral_projector.webp',
    cost: 600,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },

  // ==========================================
  // EXPANDED RPG ITEMS (50 ASSETS PACK)
  // ==========================================
  // Category A: Weapons & Combat Gear
  {
    id: 'bow-bowie',
    name: 'Bowie',
    description: 'A simple starter wooden bow - every ranger starts somewhere! Grants first strike in dungeon battles.',
    type: 'weapon',
    category: 'weapon',
    rarity: 'common',
    stats: { attack: 3 },
    emoji: '🏹',
    image: '/images/items/sword/bow-bowie.webp',
    cost: 35,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'sword-knightly',
    name: 'Knight broadsword',
    description: 'A balanced steel broadsword favored by castle guards and stalwart knights.',
    type: 'weapon',
    category: 'weapon',
    rarity: 'rare',
    stats: { attack: 8 },
    emoji: '⚔️',
    image: '/images/items/sword/sword-irony.webp',
    cost: 260,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'axe-bearded',
    name: 'Bearded battleaxe',
    description: 'A vicious double-bladed axe that cleaves through enemy frontlines.',
    type: 'weapon',
    category: 'weapon',
    rarity: 'epic',
    stats: { attack: 14 },
    emoji: '🪓',
    image: '/images/items/sword/sword-solaraxe.webp',
    cost: 550,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'shield-lionheart',
    name: 'Lionheart shield',
    description: 'An ornate heater shield emblazoned with the royal lion; absorbs critical hits.',
    type: 'shield',
    category: 'shield',
    rarity: 'epic',
    stats: { defense: 12, health: 15 },
    emoji: '🛡️',
    image: '/images/items/shield/shield-shellow.webp',
    cost: 450,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-cowl',
    name: 'Shadow cowl',
    description: 'A hooded cowl woven from midnight thread; enhances scout stealth and evasion.',
    type: 'armor',
    category: 'armor',
    rarity: 'rare',
    stats: { defense: 4, movement: 3 },
    emoji: '🥷',
    image: '/images/items/armor/armor-darko.webp',
    cost: 280,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'armor-helm-crusader',
    name: 'Crusader helm',
    description: 'A polished steel barbuta helm that protects the wearer from concussive blows.',
    type: 'armor',
    category: 'armor',
    rarity: 'epic',
    stats: { defense: 9, health: 10 },
    emoji: '🪖',
    image: '/images/items/armor/armor-silvo.webp',
    cost: 45000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-traveler',
    name: 'Traveler boots',
    description: 'Reinforced leather boots that quicken airship journeys and overland march speed.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'uncommon',
    stats: { movement: 8, defense: 4, attack: 1 },
    emoji: '👢',
    image: '/images/items/footwear/boots-traveler.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-hunter',
    name: 'Hunter boots',
    description: 'Supple deerskin boots that muffle footfalls and improve agility.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'uncommon',
    stats: { movement: 6, defense: 3 },
    emoji: '🥾',
    image: '/images/items/footwear/boots-hunter.webp',
    cost: 850,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-iron-greaves',
    name: 'Iron greaves',
    description: 'Heavy plate greaves providing solid dungeon battle deflection.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'rare',
    stats: { defense: 12, movement: 4 },
    emoji: '🛡️',
    image: '/images/items/footwear/boots-iron-greaves.webp',
    cost: 5500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-shadow-walkers',
    name: 'Shadow walkers',
    description: 'Midnight-dyed stalker boots granting high quickness and stealth.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'rare',
    stats: { movement: 14, attack: 5, defense: 4 },
    emoji: '👣',
    image: '/images/items/footwear/boots-shadow-walkers.webp',
    cost: 9200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-spellstrider',
    name: 'Spellstrider boots',
    description: 'Runed silk boots that quicken arcane casting and glide over rough terrain.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'epic',
    stats: { movement: 12, defense: 8, mana: 35 },
    emoji: '✨',
    image: '/images/items/footwear/boots-spellstrider.webp',
    cost: 38000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-dragonscale',
    name: 'Dragonscale sabatons',
    description: 'Legendary boots forged from volcanic dragon scales, impervious to molten heat.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'legendary',
    stats: { defense: 22, attack: 8, movement: 10, health: 40 },
    emoji: '🐉',
    image: '/images/items/footwear/boots-dragonscale.webp',
    cost: 180000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'boots-steel-sabatons',
    name: 'Steel sabatons',
    description: 'Masterwork polished knight greaves with engraved heraldic scrollwork, offering elite defensive protection.',
    type: 'footwear',
    category: 'footwear',
    rarity: 'rare',
    stats: { defense: 16, movement: 6, health: 20 },
    emoji: '👢',
    image: '/images/items/footwear/boots-steel-sabatons.webp',
    cost: 12500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'gauntlets-archer',
    name: 'Archer gauntlets',
    description: 'Flexible leather bracers that steady bow strings and quicken hammer blows.',
    type: 'armor',
    category: 'armor',
    rarity: 'rare',
    stats: { attack: 4, defense: 3 },
    emoji: '🧤',
    image: '/images/items/armor/armor-darko.webp',
    cost: 8500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'flail-heavy',
    name: 'Heavy war flail',
    description: 'A brutal spiked iron flail designed to shatter shields and stagger stone golems.',
    type: 'weapon',
    category: 'weapon',
    rarity: 'epic',
    stats: { attack: 13, stamina: 5 },
    emoji: '🔨',
    image: '/images/items/sword/flail-iron.webp',
    cost: 50000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'quiver-fletched',
    name: 'Leather quiver',
    description: 'An archer off-hand quiver filled with balanced arrows; amplifies bow attacks by +15%.',
    type: 'shield',
    category: 'shield',
    rarity: 'uncommon',
    stats: { attack: 4, defense: 2 },
    emoji: '🏹',
    image: '/images/items/sword/quiver-leather.webp',
    cost: 1200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },

  // Category B: Survival, Healing & Shelter
  {
    id: 'potion-elixir-vigor',
    name: 'Elixir of vigor',
    description: 'A revitalizing green draught that purges combat ailments and restores 30 HP.',
    type: 'potion',
    category: 'consumable',
    rarity: 'rare',
    stats: { health: 30, stamina: 20 },
    emoji: '🧪',
    image: '/images/items/potion/potion-protection.webp',
    cost: 450,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'tool-lantern',
    name: 'Brass lantern',
    description: 'Illuminates dark dungeon floors to reveal secret chambers; gives +15% gold on night habits.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { gold: 15 },
    emoji: '🏮',
    image: '/images/items/materials/tool-lantern.webp',
    cost: 8500,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'tool-torch',
    name: 'Pine torch',
    description: 'A resinous burning torch that prevents ambushes and burns cobwebs in dungeon delves.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'common',
    stats: { attack: 1 },
    emoji: '🔥',
    image: '/images/items/materials/tool-lantern.webp',
    cost: 20,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'bedroll-traveler',
    name: 'Traveler bedroll',
    description: 'A cozy bedroll. Resting before bed gives +25% exp on tomorrow morning habits.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { experience: 25 },
    emoji: '🛏️',
    image: '/images/items/materials/shelter-tent.webp',
    cost: 80,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'shelter-tent',
    name: 'Traveler tent',
    description: 'Field rest camp shelter. Pitch between dungeon encounters to restore 50% HP across all squad fighters!',
    type: 'consumable',
    category: 'consumable',
    rarity: 'rare',
    stats: { health: 50 },
    emoji: '⛺',
    image: '/images/items/materials/shelter-tent.webp',
    cost: 250,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // Category C: Exploration, Keys & Logistics
  {
    id: 'currency-gold-pile',
    name: 'Stack of sovereigns',
    description: 'A gleaming stack of minted realm coins. Use to immediately claim +100 gold.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { gold: 100 },
    emoji: '🪙',
    image: '/images/items/materials/currency-pouch.webp',
    cost: 100,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'currency-pouch',
    name: 'Coin pouch',
    description: 'A tied leather purse containing 45 gold from daily merchant trading.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'common',
    stats: { gold: 45 },
    emoji: '👛',
    image: '/images/items/materials/currency-pouch.webp',
    cost: 45,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'chest-lockbox',
    name: 'Ancient lockbox',
    description: 'A brass-bound chest containing forgotten scrolls, blueprints, or essence crystals.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'rare',
    stats: {},
    emoji: '📦',
    image: '/images/items/materials/lockbox-ancient.webp',
    cost: 180,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'scroll-decree',
    name: 'Royal decree',
    description: 'An official seal of the crown; immediately triggers a double-tax harvest across ready producers.',
    type: 'scroll',
    category: 'scroll',
    rarity: 'rare',
    stats: { gold: 50 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-memento.webp',
    cost: 300,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'map-treasure',
    name: 'Weathered treasure map',
    description: 'An old parchment showing a hidden X; reveals a buried treasure cache on the kingdom grid.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'rare',
    stats: { experience: 40 },
    emoji: '🗺️',
    image: '/images/items/scroll/map-treasure.webp',
    cost: 200,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'key-skeleton',
    name: 'Skeleton key',
    description: 'An ornate golden key that effortlessly unlocks locked dungeon vaults or titan victory chests.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: {},
    emoji: '🗝️',
    image: '/images/items/materials/key-skeleton.webp',
    cost: 400,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'storage-barrel',
    name: 'Oak storage barrel',
    description: 'Reinforced wood barrel that expands local brewery, tavern, and bakery tax holding buffers.',
    type: 'material',
    category: 'material',
    rarity: 'uncommon',
    stats: {},
    emoji: '🛢️',
    image: '/images/items/materials/storage-barrel.webp',
    cost: 75,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'storage-crate',
    name: 'Cargo crate',
    description: 'A sturdy timber shipping box that increases kingdom settlement harvest capacity.',
    type: 'material',
    category: 'material',
    rarity: 'uncommon',
    stats: {},
    emoji: '🪵',
    image: '/images/items/materials/storage-crate.webp',
    cost: 60,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-grain-sack',
    name: 'Burlap grain sack',
    description: 'A heavy sack of milled flour and grain; feeds multiple hungry citizens in one tap.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'common',
    stats: { stamina: 30 },
    emoji: '🌾',
    image: '/images/items/food/food-grain-sack.webp',
    cost: 40,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-hardtack',
    name: 'Hardtack ration',
    description: 'Dry, long-lasting baked ship biscuits that sustain long ether voyages and dungeon delves.',
    type: 'food',
    category: 'consumable',
    rarity: 'common',
    stats: { health: 10, stamina: 15 },
    emoji: '🍘',
    image: '/images/items/food/food-hardtack.webp',
    cost: 25,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-salted-beef',
    name: 'Salted beef',
    description: 'Cured timber-smoked beef rich in protein, granting sustained vitality to fighters and workers.',
    type: 'food',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { health: 30, stamina: 35 },
    emoji: '🥩',
    image: '/images/items/food/food-salted-beef.webp',
    cost: 120,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'drink-honeyed-mead',
    name: 'Spiced mead',
    description: 'Fermented golden honey infused with winter spices; restores mana and morale.',
    type: 'consumable',
    category: 'consumable',
    rarity: 'uncommon',
    stats: { mana: 25, stamina: 25 },
    emoji: '🍺',
    image: '/images/items/food/drink-honeyed-mead.webp',
    cost: 160,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'food-royal-pastry',
    name: 'Gourmet pastry',
    description: 'Delicate butter pastries baked with royal preserve fruits, favored by kingdom nobles.',
    type: 'food',
    category: 'consumable',
    rarity: 'rare',
    stats: { health: 50, mana: 40, stamina: 50 },
    emoji: '🥐',
    image: '/images/items/food/food-royal-pastry.webp',
    cost: 450,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'material-damascus-steel',
    name: 'Damascus steel',
    description: 'Folded masterwork steel with distinctive wavy patterns, used for high-tier forge armaments.',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: {},
    emoji: '⛓️',
    image: '/images/items/materials/material-damascus-steel.webp',
    cost: 2500,
    isDefault: false,
    isEquippable: false,
    isConsumable: false,
  },
  {
    id: 'trophy-wyrm-fang',
    name: 'Titan wyrm fang',
    description: 'A massive crystallized fang recovered from a defeated Alliance Titan Wyrm.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'legendary',
    stats: { attack: 15, defense: 10 },
    emoji: '🦷',
    image: '/images/items/materials/trophy-wyrm-fang.webp',
    cost: 25000,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'material-gold-bullion',
    name: 'Gold bullion',
    description: 'A pure cast gold bar worth 250 gold; used for monument construction or market trade.',
    type: 'material',
    category: 'material',
    rarity: 'epic',
    stats: { gold: 250 },
    emoji: '🧈',
    image: '/images/items/materials/material-gold.webp',
    cost: 250,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // Category D: Elemental Crystals & Botanical Reagents
  {
    id: 'crystal-sapphire',
    name: 'Sapphire crystal',
    description: 'A luminous azure crystal pulsing with Knowledge virtue; used in high alchemy and Mage training.',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: { mana: 15 },
    emoji: '🔷',
    image: '/images/items/materials/material-crystal.webp',
    cost: 160,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'crystal-ruby',
    name: 'Ruby crystal',
    description: 'A fiery crimson crystal pulsing with Might virtue; used in Blacksmith flame forging and Tank training.',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: { attack: 3 },
    emoji: '🔴',
    image: '/images/items/materials/material-crystal.webp',
    cost: 160,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'crystal-emerald',
    name: 'Emerald crystal',
    description: 'A verdant green crystal pulsing with Vitality virtue; used for garden growth and health alchemy.',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: { health: 25 },
    emoji: '🟢',
    image: '/images/items/materials/material-crystal.webp',
    cost: 160,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'crystal-amethyst',
    name: 'Amethyst crystal',
    description: 'A royal violet crystal pulsing with Honor virtue; used for Astral Citadel monuments and Mythics.',
    type: 'material',
    category: 'material',
    rarity: 'epic',
    stats: { defense: 5 },
    emoji: '🟣',
    image: '/images/items/materials/material-crystal.webp',
    cost: 280,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'reagent-starflower',
    name: 'Silver starflower',
    description: 'A pure nocturnal blossom; fed to Guardian Pets (+15% affection) or brewed into supreme draughts.',
    type: 'material',
    category: 'material',
    rarity: 'rare',
    stats: {},
    emoji: '🌸',
    image: '/images/items/materials/material-crystal.webp',
    cost: 120,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'reagent-feverfew',
    name: 'Feverfew sprig',
    description: 'A fragrant medicinal herb; the core botanical ingredient required to brew Health potions.',
    type: 'material',
    category: 'material',
    rarity: 'common',
    stats: {},
    emoji: '🌿',
    image: '/images/items/materials/material-apple.webp',
    cost: 15,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'reagent-toadstool',
    name: 'Spotted toadstool',
    description: 'A speckled red forest mushroom; used in the Apotheca to craft coatings and explosive flasks.',
    type: 'material',
    category: 'material',
    rarity: 'uncommon',
    stats: {},
    emoji: '🍄',
    image: '/images/items/materials/material-apple.webp',
    cost: 35,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },

  // Category E: Relics, Rings & Lore Artifacts
  {
    id: 'ring-ruby',
    name: 'Ruby signet ring',
    description: 'A polished gold ring set with a glowing ruby; grants +5 ATK and +5% Might virtue energy.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { attack: 5 },
    emoji: '💍',
    image: '/images/items/artifact/ring/ring-ruby.webp',
    cost: 420,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'ring-sapphire',
    name: 'Sapphire band',
    description: 'A silver band with a celestial sapphire; grants +15 Mana and +5% Knowledge virtue energy.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { defense: 5, attack: 3, mana: 15 },
    emoji: '💍',
    image: '/images/items/artifact/ring/artifact-ringo.webp',
    cost: 420,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'ring-emerald',
    name: 'Emerald loop',
    description: 'A gold ring clutching a radiant emerald; grants +25 HP and +5% Vitality virtue energy.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { health: 25, defense: 6, attack: 2 },
    emoji: '💍',
    image: '/images/items/artifact/ring/ring-emerald.webp',
    cost: 420,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'pendant-amethyst',
    name: 'Amethyst amulet',
    description: 'A teardrop amethyst pendant that shields against boss elemental spells (+8 DEF).',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { defense: 10, attack: 4, mana: 20 },
    emoji: '📿',
    image: '/images/items/artifact/pendant-amethyst.webp',
    cost: 680,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'medallion-sun',
    name: 'Sunburst medallion',
    description: 'A golden sun pendant; grants +10% bonus gold on habits completed before noon.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { attack: 6, defense: 4, gold: 10 },
    emoji: '☀️',
    image: '/images/items/materials/medallion-sun.webp',
    cost: 750,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'talisman-moon',
    name: 'Moon talisman',
    description: 'A crescent lapis talisman; grants +10% bonus gold on evening habits completed after dusk.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { defense: 6, attack: 4, gold: 10 },
    emoji: '🌙',
    image: '/images/items/materials/talisman-moon.webp',
    cost: 750,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-imperial-crown',
    name: 'Monarch crown',
    description: 'An imperial golden crown set with jewels; boosts passive tax yields across all districts by +10%.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'legendary',
    stats: { defense: 12, attack: 6, health: 50, gold: 20 },
    emoji: '👑',
    image: '/images/items/artifact/crown/artifact-crowny.webp',
    cost: 2200,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'artifact-chalice',
    name: 'Ceremonial chalice',
    description: 'A bejeweled gold goblet; toasting circle allies in alliance raids yields +5 House Cup points.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { defense: 5, attack: 4, mana: 30 },
    emoji: '🏆',
    image: '/images/items/artifact/artifact-chalice.webp',
    cost: 950,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'book-grimoire',
    name: 'Tome of arcana',
    description: 'An ancient leather-bound spellbook; unlocks extra elemental combat options in Dungeon Keep.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { attack: 8, defense: 4, mana: 40 },
    emoji: '📖',
    image: '/images/items/scroll/book-grimoire.webp',
    cost: 880,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'scroll-runic',
    name: 'Runic parchment',
    description: 'Ancient spiral runes; grants an immediate rune discovery insight for the Rune Lore Compendium.',
    type: 'scroll',
    category: 'scroll',
    rarity: 'rare',
    stats: { experience: 80 },
    emoji: '📜',
    image: '/images/items/scroll/scroll-memento.webp',
    cost: 350,
    isDefault: false,
    isEquippable: false,
    isConsumable: true,
  },
  {
    id: 'tool-quill',
    name: 'Scribe quill',
    description: 'A pure white quill feather; doubles virtue exp gained from Chronicle journal reflections.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'uncommon',
    stats: { defense: 3, attack: 2, experience: 20 },
    emoji: '🪶',
    image: '/images/items/materials/tool-quill.webp',
    cost: 150,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'curio-skull',
    name: 'Memento mori',
    description: 'An ancient carved skull: "Remember that time is finite" — grants +10% streak exp.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'rare',
    stats: { attack: 5, defense: 3, experience: 30 },
    emoji: '💀',
    image: '/images/items/materials/curio-skull.webp',
    cost: 380,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  },
  {
    id: 'relic-horse',
    name: 'Equine statuette',
    description: 'A gilded horse figurine; doubles mount galloping speed and shortens airship voyage times.',
    type: 'artifact',
    category: 'artifact',
    rarity: 'epic',
    stats: { movement: 14, attack: 4, defense: 4 },
    emoji: '🐎',
    image: '/images/items/horse/horse-goldy.webp',
    cost: 900,
    isDefault: false,
    isEquippable: true,
    isConsumable: false,
  }
];

// Helper functions
export const getItemById = (id: string): ComprehensiveItem | undefined => {
  return comprehensiveItems.find(item => item.id === id);
};

export const getItemsByType = (type: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.type === type);
};

export const getItemsByCategory = (category: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.category === category);
};

export const getItemsByRarity = (rarity: string): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.rarity === rarity);
};

export const getEquippableItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isEquippable);
};

export const getConsumableItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isConsumable);
};

export const getDefaultItems = (): ComprehensiveItem[] => {
  return comprehensiveItems.filter(item => item.isDefault);
};
