import { InventoryItem } from "@/types/tiles";

export const initialTiles: InventoryItem[] = [
  {
    id: "grass-1",
    type: "grass",
    name: "Grass Tile",
    description: "A lush grass tile",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Grass tile",
    image: "/images/tiles/grass-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "water-1",
    type: "water",
    name: "Water Tile",
    description: "A body of water",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Water tile",
    image: "/images/tiles/water-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "forest-1",
    type: "forest",
    name: "Forest Tile",
    description: "A dense forest area",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Forest tile",
    image: "/images/tiles/forest-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "mountain-1",
    type: "mountain",
    name: "Mountain Tile",
    description: "A towering mountain peak",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Mountain tile",
    image: "/images/tiles/mountain-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "desert-1",
    type: "desert",
    name: "Desert Tile",
    description: "A hot desert",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Desert tile",
    image: "/images/tiles/desert-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "ice-1",
    type: "ice",
    name: "Ice Tile",
    description: "A frozen ice tile",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Ice tile",
    image: "/images/tiles/ice-tile.png",
    cost: 100,
    quantity: 10
  },
  {
    id: "town-1",
    type: "town",
    name: "Town Tile",
    description: "A small town",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "Town tile",
    image: "/images/tiles/town-tile.png",
    cost: 200,
    quantity: 5
  },
  {
    id: "city-1",
    type: "city",
    name: "City Tile",
    description: "A bustling city",
    connections: [],
    rotation: 0,
    revealed: true,
    isVisited: false,
    x: 0,
    y: 0,
    ariaLabel: "City tile",
    image: "/images/tiles/city-tile.png",
    cost: 300,
    quantity: 3
  }
]; 