'use client'

import React, { useState, useEffect } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { BookOpen, Sparkles, CheckCircle2, XCircle, HelpCircle } from 'lucide-react'
import { useToast } from '@/components/ui/use-toast'
import { addToCharacterStat } from '@/lib/character-stats-service'

interface AncientRiddleModalProps {
  isOpen: boolean
  onClose: () => void
}

const TOWN_RIDDLES = [
  {
    id: 'r-1',
    question: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
    options: ["A Realm Map", "A Magic Globe", "A Tapestry", "A Mirror"],
    correctIndex: 0,
    rewardDesc: "+150 Gold & 1x Kingdom Blueprint Scroll"
  },
  {
    id: 'r-2',
    question: "I am forged in dragonfire and wielded by Round Table champions to slay keep monsters. What am I?",
    options: ["A Sovereign Blade", "An Oak Shield", "A Blacksmith Hammer", "A Magic Wand"],
    correctIndex: 0,
    rewardDesc: "+200 Gold & 2x Steel Blocks"
  },
  {
    id: 'r-3',
    question: "I rise when you check in, reset at local midnight, and decay if you miss a day. What am I?",
    options: ["A Habit Streak", "A Dungeon Timer", "A Tax Harvest", "A Spell Cooldown"],
    correctIndex: 0,
    rewardDesc: "+180 Gold & 1x Streak Freeze Shield"
  },
  {
    id: 'r-4',
    question: "I glow with purple crystal magic atop the Astral Citadel, crowning the realm treasury. What am I?",
    options: ["An Astral Crystal Orb", "A Sunburst Shard", "A Mana Potion", "A Magic Lamp"],
    correctIndex: 0,
    rewardDesc: "+250 Gold & 1x Astral Monument Blueprint"
  },
  {
    id: 'r-5',
    question: "I turn botanical herbs and spring water into gold, exp, and health potions in the glasshouse. What am I?",
    options: ["The Grand Apotheca", "The Town Bakery", "The Blacksmith Forge", "The Royal Stables"],
    correctIndex: 0,
    rewardDesc: "+220 Gold & 3x Botanical Reagents"
  },
  {
    id: 'r-6',
    question: "I am built with 84 placeable tiles, from serene lakes to floating islands. What am I?",
    options: ["The Realm Sandbox Grid", "The Dungeon Labyrinth", "The Airship Deck", "The City Gate"],
    correctIndex: 0,
    rewardDesc: "+200 Gold & 1x Serene Lake Blueprint"
  },
  {
    id: 'r-7',
    question: "I am completed 5 times a day for a Great score, 10 times for Awesome, and 15 times for Super. What am I?",
    options: ["Sovereign Habit Cadence", "Monster Encounters", "Dice Rolls", "Airship Voyages"],
    correctIndex: 0,
    rewardDesc: "+175 Gold & 100 Character XP"
  },
  {
    id: 'r-8',
    question: "I fly on Ether fuel generated by Knowledge and Might habits to trade at distant ports. What am I?",
    options: ["The Airship Harbor Voyage", "A Carrier Pigeon", "A Dragon Mount", "A Weather Balloon"],
    correctIndex: 0,
    rewardDesc: "+210 Gold & 50 Ether Fuel"
  },
  {
    id: 'r-9',
    question: "I protect your streak when a day is missed, freezing decay until you check in. What am I?",
    options: ["A Streak Scroll Shield", "A Health Elixir", "A City Tax Token", "A Paragon Crest"],
    correctIndex: 0,
    rewardDesc: "+190 Gold & 1x Streak Scroll"
  },
  {
    id: 'r-10',
    question: "I carry 7 virtue hourglasses measuring Might, Knowledge, Honor, Castle, Craft, Vitality, and Wellness. What am I?",
    options: ["The House Cup", "The Town Clock", "The Dungeon Altar", "The Market Scale"],
    correctIndex: 0,
    rewardDesc: "+300 Gold & +10 Virtue Points"
  }
]

export function AncientRiddleModal({ isOpen, onClose }: AncientRiddleModalProps) {
  const { toast } = useToast()
  const [riddle, setRiddle] = useState(TOWN_RIDDLES[0]!)
  const [selectedOpt, setSelectedOpt] = useState<number | null>(null)
  const [isAnswered, setIsAnswered] = useState(false)
  const [isCorrect, setIsCorrect] = useState(false)

  useEffect(() => {
    if (!isOpen) return
    const today = new Date().toDateString()
    const lastRiddle = localStorage.getItem('town_riddle_solve_date')
    
    // Pick a random unique riddle each day
    const dayHash = (new Date().getFullYear() * 365 + new Date().getMonth() * 30 + new Date().getDate()) % TOWN_RIDDLES.length
    const todaysRiddle = TOWN_RIDDLES[dayHash] || TOWN_RIDDLES[0]!
    setRiddle(todaysRiddle)

    if (lastRiddle === today) {
      setIsAnswered(true)
      setIsCorrect(true)
    } else {
      setIsAnswered(false)
      setIsCorrect(false)
      setSelectedOpt(null)
    }
  }, [isOpen])

  const handleSelectOption = async (index: number) => {
    if (isAnswered) return
    setSelectedOpt(index)
    setIsAnswered(true)

    if (index === riddle.correctIndex) {
      setIsCorrect(true)
      const today = new Date().toDateString()
      localStorage.setItem('town_riddle_solve_date', today)
      await addToCharacterStat('gold', 200, 'town-riddle-solve')
      toast({
        title: "📜 Town Riddle Solved!",
        description: `Correct! Awarded ${riddle.rewardDesc}.`,
      })
    } else {
      setIsCorrect(false)
      toast({
        title: "❌ Incorrect Answer",
        description: "The town scholar's scroll remains sealed today. Return tomorrow!",
        variant: "destructive"
      })
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={(op) => { if (!op) onClose() }}>
      <DialogContent className="max-w-md w-full bg-gradient-to-b from-blue-950 via-zinc-950 to-zinc-950 border border-blue-500/40 text-blue-100 p-6 rounded-2xl shadow-2xl font-serif text-center overflow-hidden z-[100]">
        <DialogHeader>
          <div className="mx-auto w-12 h-12 rounded-full bg-blue-500/20 border border-blue-400 flex items-center justify-center mb-2 shadow-[0_0_20px_rgba(59,130,246,0.4)]">
            <BookOpen className="w-6 h-6 text-blue-300 animate-pulse" />
          </div>
          <DialogTitle className="text-2xl font-medieval text-blue-200">
            Town Scholar&apos;s Ancient Riddle
          </DialogTitle>
          <DialogDescription className="text-xs text-zinc-400 italic">
            Solve today&apos;s unique town lore riddle to unearth blueprints, virtue points, and gold.
          </DialogDescription>
        </DialogHeader>

        <div className="my-4 p-4 bg-zinc-950/90 rounded-2xl border border-blue-900/40 space-y-4 text-left">
          <p className="text-sm font-bold text-amber-200 leading-relaxed italic border-b border-blue-900/30 pb-3">
            &ldquo;{riddle.question}&rdquo;
          </p>

          <div className="space-y-2">
            {riddle.options.map((opt, idx) => {
              let btnStyle = "bg-zinc-900 border-zinc-800 text-zinc-300 hover:border-blue-500/50"
              if (isAnswered) {
                if (idx === riddle.correctIndex) btnStyle = "bg-emerald-950 border-emerald-500 text-emerald-200"
                else if (selectedOpt === idx) btnStyle = "bg-red-950 border-red-500 text-red-200"
              }
              return (
                <button
                  key={idx}
                  disabled={isAnswered}
                  onClick={() => handleSelectOption(idx)}
                  className={`w-full p-3 rounded-xl border text-xs font-bold text-left transition-all flex items-center justify-between cursor-pointer ${btnStyle}`}
                >
                  <span>{opt}</span>
                  {isAnswered && idx === riddle.correctIndex && <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />}
                  {isAnswered && selectedOpt === idx && idx !== riddle.correctIndex && <XCircle className="w-4 h-4 text-red-400 shrink-0" />}
                </button>
              )
            })}
          </div>

          {isAnswered && isCorrect && (
            <div className="p-3 bg-emerald-950/60 border border-emerald-500/40 rounded-xl text-xs text-emerald-300 font-bold text-center animate-in fade-in">
              ✨ Reward Unlocked: {riddle.rewardDesc}
            </div>
          )}
        </div>

        <Button
          onClick={onClose}
          className="w-full py-2.5 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white font-bold uppercase tracking-wider text-xs shadow-lg"
        >
          {isAnswered ? 'Close Scroll' : 'Cancel'}
        </Button>
      </DialogContent>
    </Dialog>
  )
}
