ALTER TABLE dungeon_runs
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'completed',
    ADD COLUMN IF NOT EXISTS current_room INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_hp INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_hp INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_rooms INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_encounter JSONB DEFAULT '{}'::jsonb;