INSERT INTO achievement_definitions (
        id,
        name,
        description,
        category,
        difficulty,
        xp_reward,
        gold_reward,
        image_url,
        unlock_condition
    )
VALUES (
        '001',
        'Flamio',
        'A fiery creature awakened by any forest destruction.',
        'exploration',
        'easy',
        100,
        50,
        '/images/creatures/Flamio.png',
        'Destroy 1 Forest'
    ),
    (
        '002',
        'Embera',
        'A more powerful fire entity born from continued forest destruction.',
        'exploration',
        'medium',
        200,
        100,
        '/images/creatures/Embera.png',
        'Destroy 5 Forests'
    ),
    (
        '003',
        'Vulcana',
        'The ultimate fire creature, master of forest destruction.',
        'exploration',
        'hard',
        500,
        250,
        '/images/creatures/Vulcana.png',
        'Destroy 10 Forests'
    ),
    (
        '004',
        'Dolphio',
        'A playful water creature that appears when expanding water territories.',
        'exploration',
        'easy',
        100,
        50,
        '/images/creatures/Dolphio.png',
        'Place 1 Water'
    ),
    (
        '005',
        'Divero',
        'A more experienced water dweller, guardian of expanding waters.',
        'exploration',
        'medium',
        200,
        100,
        '/images/creatures/Divero.png',
        'Place 5 Water'
    ),
    (
        '006',
        'Flippur',
        'The supreme water creature, master of vast water territories.',
        'exploration',
        'hard',
        500,
        250,
        '/images/creatures/Flippur.png',
        'Place 10 Water'
    ),
    (
        '007',
        'Leaf',
        'A small grass creature that appears when planting new forests.',
        'exploration',
        'easy',
        100,
        50,
        '/images/creatures/Leaf.png',
        'Place 1 Forest'
    ),
    (
        '008',
        'Oaky',
        'A stronger forest guardian, protector of growing woodlands.',
        'exploration',
        'medium',
        200,
        100,
        '/images/creatures/Oaky.png',
        'Place 5 Forest'
    ),
    (
        '009',
        'Seqoio',
        'The mighty forest spirit, overseer of vast woodlands.',
        'exploration',
        'hard',
        500,
        250,
        '/images/creatures/Seqoio.png',
        'Place 10 Forest'
    ),
    (
        '010',
        'Rockie',
        'A small rock creature that emerges from destroyed mountains.',
        'exploration',
        'easy',
        100,
        50,
        '/images/creatures/Rockie.png',
        'Destroy 1 Mountain'
    ),
    (
        '011',
        'Buldour',
        'A stronger mountain spirit, born from continued destruction.',
        'exploration',
        'medium',
        200,
        100,
        '/images/creatures/Buldour.png',
        'Destroy 5 Mountains'
    ),
    (
        '012',
        'Montano',
        'The ultimate mountain creature, master of destroyed peaks.',
        'exploration',
        'hard',
        500,
        250,
        '/images/creatures/Montano.png',
        'Destroy 10 Mountains'
    ),
    (
        '013',
        'IceCube',
        'A small ice creature born from placing ice tiles.',
        'exploration',
        'easy',
        100,
        50,
        '/images/creatures/IceCube.png',
        'Place 1 Ice'
    ),
    (
        '014',
        'Iciclo',
        'A sharp ice spirit responding to expanded frozen lands.',
        'exploration',
        'medium',
        200,
        100,
        '/images/creatures/Iciclo.png',
        'Place 5 Ice'
    ),
    (
        '015',
        'Glacior',
        'The ruler of the frozen wastes, master of ice placement.',
        'exploration',
        'hard',
        500,
        250,
        '/images/creatures/Glacior.png',
        'Place 10 Ice'
    ) ON CONFLICT (id) DO
UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    xp_reward = EXCLUDED.xp_reward,
    gold_reward = EXCLUDED.gold_reward,
    image_url = EXCLUDED.image_url,
    unlock_condition = EXCLUDED.unlock_condition;