export interface Chapter {
    id: number;
    title: string;
    description: string;
    levelRequirement: number; // User level required to unlock
    image?: string; // Placeholder for future images
}

export const CHRONICLES_DATA: Chapter[] = [
    {
        id: 1,
        title: "The Awakening",
        description: "The Realm of Valoreth lay dormant, its skies gray and its fields silent. For generations, the land had slept, waiting for a ruler whose daily actions could breathe life back into its soil. When you arrived, the Grand Citadel was little more than a memory carved in stone. But as you set your first goals and completed your first tasks, a spark of Essence materialized in the air. The Realm responded not to sword or spell, but to your consistency and focus. The journey to rebuild the Kingdom had begun.",
        levelRequirement: 1
    },
    {
        id: 2,
        title: "The First Companion",
        description: "As the first golden sunbeams pierced the overcast sky, drawn by your growing momentum, a creature emerged from the Whispering Woods. This was no mere beast, but a Citizen of Valoreth, drawn to the Essence generated by your daily habits. By designating them as your Partner, a deep bond was forged. You realized that the stronger you became in your own life, the more Essence you could share, helping your companion grow alongside you.",
        levelRequirement: 10
    },
    {
        id: 3,
        title: "Laying the Foundations",
        description: "With a loyal Partner at your side, your ambitions grew. The gold earned from your daily quests began to fund the reconstruction of the Kingdom. The first tiles were laid: a humble farm, a bustling bakery, a sturdy blacksmith. These were not mere decorations; they were the beating heart of your new civilization. The more consistent you remained, the faster your Kingdom thrived, proving that true leadership is built day by day.",
        levelRequirement: 20
    },
    {
        id: 4,
        title: "A Gathering of Citizens",
        description: "Word of your flourishing Kingdom spread across the land. From the Crystal Caverns to the Endless Frost, Mythic Packs were discovered, revealing rare and wondrous creatures eager to join your cause. As you scratched away the seals, new Citizens arrived, bringing vibrant life to your Realm. You provided them with sustenance, and in return, they wandered your lands, passively generating the resources needed to expand your empire.",
        levelRequirement: 30
    },
    {
        id: 5,
        title: "The Weather's Will",
        description: "You soon learned that Valoreth was intrinsically tied to your inner state. On days when your discipline faltered and tasks were left undone, the Kingdom's skies darkened, casting a stormy overcast shadow over the realm. But when you held your focus and maintained a high momentum, the clouds parted. The Kingdom basked in a radiant, golden glow, a direct reflection of your personal triumphs.",
        levelRequirement: 40
    },
    {
        id: 6,
        title: "The Power of Evolution",
        description: "Your Partner had absorbed the Essence of countless completed habits. A profound transformation occurred. With a surge of radiant energy, your Partner evolved into a stronger, more majestic form. They unlocked new abilities and passive perks that bolstered your own productivity. It was a beautiful cycle: your real-world growth fueled their evolution, and their evolution empowered your continued success.",
        levelRequirement: 50
    },
    {
        id: 7,
        title: "The Flourishing City",
        description: "The Kingdom was no longer a mere outpost; it was a sprawling, functional metropolis. The Library granted immense wisdom, accelerating your experience. The Bakery and Blacksmith hummed with constant activity. The grid was a testament to your strategic planning and unwavering dedication. Valoreth was alive, bustling with Citizens and glowing with the prosperity of a well-maintained realm.",
        levelRequirement: 60
    },
    {
        id: 8,
        title: "The Archive of Triumphs",
        description: "To honor the legends forged during your reign, the Archive of Triumphs was constructed. Here, the greatest of your Citizens—those who had reached the pinnacle of their potential—were immortalized as grand stone statues. Walking through the museum, you could see the lifetime statistics of your heroes. They stood as enduring monuments to the habits and challenges you had conquered together.",
        levelRequirement: 70
    },
    {
        id: 9,
        title: "The Mythic Horizon",
        description: "Your journey led you to the discovery of legendary Mythic and Holographic variants. These rare beings were drawn only to rulers of unparalleled discipline. Unlocking them required immense dedication, but their presence in the Realm elevated your Kingdom to unprecedented heights. They were the ultimate reward for a life lived with purpose and consistency.",
        levelRequirement: 80
    },
    {
        id: 10,
        title: "Master of the Realm",
        description: "You had become more than a ruler; you were the very catalyst of Valoreth's existence. The Tripartite systems—your Partner's bond, the wandering Citizens, and the bustling Kingdom—operated in perfect harmony. Your real-world actions flowed seamlessly into the digital realm, creating an unbreakable loop of positive reinforcement. The shadows of stagnation were banished forever.",
        levelRequirement: 90
    },
    {
        id: 11,
        title: "Epilogue: The Eternal Kingdom",
        description: "Valoreth stands as a beacon of your unwavering resolve. The skies are forever shaped by your momentum, your Citizens thrive under your care, and your Partner walks beside you in their ultimate form. The Grand Citadel, once a ruin, is now the heart of a vibrant world. The story of its rebuilding is complete, but your journey continues. For an Eternal Kingdom is not just built; it is maintained, day by day, through the magic of consistency.",
        levelRequirement: 100
    }
];

export function getCurrentChapter(level: number): Chapter {
    // Find the highest chapter whose requirement is met
    const chapter = CHRONICLES_DATA.slice().reverse().find(chapter => level >= chapter.levelRequirement);
    return chapter || CHRONICLES_DATA[0] as Chapter;
}

export function getNextChapter(level: number): Chapter | null {
    return CHRONICLES_DATA.find(chapter => chapter.levelRequirement > level) || null;
}
