import { Quest } from './quest-types';

export const defaultQuests: Quest[] = [
  {
    id: 'onboarding-exploration',
    title: 'Explorer of the Kingdom',
    description: 'Check this quest and delete it after visiting the Kingdom page.',
    category: 'exploration',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 20 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onboarding-might',
    title: 'Beginner Strength',
    description: 'Perform 10 jumping jacks to wake up your warrior spirit.',
    category: 'might',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 10 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onboarding-knowledge',
    title: 'Spark of Wisdom',
    description: 'Read the "Kingdom Guide" in the Help menu.',
    category: 'knowledge',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 10 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onboarding-honor',
    title: 'Self-Care Ritual',
    description: 'Complete one small grooming task today.',
    category: 'honor',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 10 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onboarding-castle',
    title: 'Orderly Domain',
    description: 'Tidy up one small area of your physical workspace.',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 10 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onboarding-vitality',
    title: 'Pure Hydration',
    description: 'Drink a full glass of water.',
    category: 'vitality',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 10 },
    progress: 0,
    completed: false,
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
