import { Quest } from './quest-types';

export const defaultQuests: Quest[] = [
  {
    id: 'pushups',
    title: '300x Pushups',
    description: '',
    category: 'might',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'plank',
    title: 'Plank 3:00',
    description: '',
    category: 'might',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'walk',
    title: 'Walk',
    description: '',
    category: 'might',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'spanish',
    title: 'Spanish',
    description: '',
    category: 'knowledge',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'piano',
    title: 'Duo Piano',
    description: '',
    category: 'knowledge',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mindpal',
    title: 'Mindpal',
    description: '',
    category: 'knowledge',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'typing',
    title: 'Quick Typing',
    description: '',
    category: 'knowledge',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'read',
    title: 'Read 5 Minutes',
    description: '',
    category: 'knowledge',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'vitamind',
    title: 'Vitamin D',
    description: '',
    category: 'knowledge',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'draw',
    title: '24 Draw Lesson',
    description: '',
    category: 'knowledge',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'academy',
    title: 'Daily Hype 4 Academy',
    description: '',
    category: 'knowledge',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'wake',
    title: 'Wake Up Before 10',
    description: '',
    category: 'honor',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'tooth',
    title: 'Toothbrushing',
    description: '',
    category: 'honor',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'handwriting',
    title: 'Handwriting',
    description: '',
    category: 'honor',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'shave',
    title: 'Shave',
    description: '',
    category: 'honor',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'barber',
    title: 'Barber',
    description: '',
    category: 'honor',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'dishwasher',
    title: 'Dishwasher',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'diaper',
    title: 'Diaper Bin',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'vacuum',
    title: 'Vacuuming',
    description: '',
    category: 'castle',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'plants',
    title: 'Water Plants',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'laundry',
    title: 'Bed Laundry',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'trash',
    title: 'Trash Bin at the Road',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'paper',
    title: 'Paper on the Road',
    description: '',
    category: 'castle',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'doodle',
    title: 'Doodle',
    description: '',
    category: 'craft',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'animate',
    title: 'Animate',
    description: '',
    category: 'craft',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'battubby',
    title: 'Battubby',
    description: '',
    category: 'vitality',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mango',
    title: 'Mango Food Fill',
    description: '',
    category: 'vitality',
    difficulty: 'easy',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'meditate',
    title: 'Meditate',
    description: 'Take time to meditate and clear your mind.',
    category: 'wellness',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 15 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'yoga',
    title: 'Do a Yoga Session',
    description: 'Complete a yoga session for flexibility and relaxation.',
    category: 'wellness',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 15 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'journal',
    title: 'Daily Journal Entry',
    description: 'Write a daily journal entry to reflect on your day.',
    category: 'wellness',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 15 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'visit-place',
    title: 'Visit a New Place',
    description: 'Explore and visit a new location.',
    category: 'exploration',
    difficulty: 'easy',
    rewards: { xp: 40, gold: 20 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'hike',
    title: 'Hike 2km',
    description: 'Go for a 2km hike in nature.',
    category: 'exploration',
    difficulty: 'medium',
    rewards: { xp: 50, gold: 25 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'new-dish',
    title: 'Try One New Dish',
    description: 'Expand your palate by trying a new dish.',
    category: 'exploration',
    difficulty: 'easy',
    rewards: { xp: 30, gold: 15 },
    progress: 0,
    completed: false,
    deadline: '',
    isNew: true,
    isAI: false,
    userId: '',
    createdAt: '',
    updatedAt: '',
  },
]; 