
export interface RiddleDefinition {
    id: string;
    question: string;
    options: string[]; // First 4 options are used, shuffling is handled by the consumer
    correctAnswer: string;
}

export const RIDDLE_DATA: RiddleDefinition[] = [
    { id: 'riddle-1', question: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?', options: ['An Echo', 'A Ghost', 'A Cloud', 'A Whisper'], correctAnswer: 'An Echo' },
    { id: 'riddle-2', question: 'The more of this there is, the less you see. What is it?', options: ['Darkness', 'Fog', 'Light', 'Smoke'], correctAnswer: 'Darkness' },
    { id: 'riddle-3', question: 'I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?', options: ['A Map', 'A Globe', 'A Painting', 'A Book'], correctAnswer: 'A Map' },
    { id: 'riddle-4', question: 'What has keys, but no locks; space, but no room; and you can enter, but not go in?', options: ['A Keyboard', 'A Piano', 'A Computer', 'A House'], correctAnswer: 'A Keyboard' },
    { id: 'riddle-5', question: 'I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by everyone. What am I?', options: ['Pencil Lead', 'Coal', 'Diamond', 'Gold'], correctAnswer: 'Pencil Lead' },
    { id: 'riddle-6', question: 'What is so fragile that saying its name breaks it?', options: ['Silence', 'Glass', 'A Secret', 'A Promise'], correctAnswer: 'Silence' },
    { id: 'riddle-7', question: 'The more you take, the more you leave behind. What are they?', options: ['Footsteps', 'Fingerprints', 'Memories', 'Time'], correctAnswer: 'Footsteps' },
    { id: 'riddle-8', question: 'What has a face and two hands but no arms or legs?', options: ['A Clock', 'A Watch', 'A Person', 'A Statue'], correctAnswer: 'A Clock' },
    { id: 'riddle-9', question: 'What gets wetter as it dries?', options: ['A Towel', 'A Sponge', 'A Cloud', 'Water'], correctAnswer: 'A Towel' },
    { id: 'riddle-10', question: 'What has a neck but no head?', options: ['A Bottle', 'A Shirt', 'A Guitar', 'A Giraffe'], correctAnswer: 'A Bottle' },
    { id: 'riddle-11', question: 'I am always coming, but never arrive. What am I?', options: ['Tomorrow', 'The Train', 'The Future', 'Death'], correctAnswer: 'Tomorrow' },
    { id: 'riddle-12', question: 'What can be broken, but is never held?', options: ['A Promise', 'A Glass', 'A Heart', 'Silence'], correctAnswer: 'A Promise' },
    { id: 'riddle-13', question: 'I have branches, but no fruit, trunk or leaves. What am I?', options: ['A Bank', 'A Library', 'A River', 'A Tree'], correctAnswer: 'A Bank' },
    { id: 'riddle-14', question: 'Feed me and I live, yet give me a drink and I die. What am I?', options: ['Fire', 'A Plant', 'A Pet', 'Hunger'], correctAnswer: 'Fire' },
    { id: 'riddle-15', question: 'What is light as a feather, but even the world\'s strongest man couldn\'t hold it for more than a minute?', options: ['Breath', 'Smoke', 'A Bubble', 'A Feather'], correctAnswer: 'Breath' },
    { id: 'riddle-16', question: 'What has a head and a tail but no body?', options: ['A Coin', 'A Snake', 'A Comet', 'A Story'], correctAnswer: 'A Coin' },
    { id: 'riddle-17', question: 'What comes once in a minute, twice in a moment, but never in a thousand years?', options: ['The letter M', 'A Leap Year', 'A Comet', 'The Moon'], correctAnswer: 'The letter M' },
    { id: 'riddle-18', question: 'I have holes in my top and bottom, my left and right, and in the middle. But I still hold water. What am I?', options: ['A Sponge', 'A Net', 'A Cup', 'A Strainer'], correctAnswer: 'A Sponge' },
    { id: 'riddle-19', question: 'If you have me, you want to share me. If you share me, you haven\'t got me. What am I?', options: ['A Secret', 'Money', 'Love', 'Advice'], correctAnswer: 'A Secret' },
    { id: 'riddle-20', question: 'What starts with T, ends with T, and has T in it?', options: ['A Teapot', 'A Tent', 'Target', 'Toast'], correctAnswer: 'A Teapot' },
    { id: 'riddle-21', question: 'I\'m tall when I\'m young, and I\'m short when I\'m old. What am I?', options: ['A Candle', 'A Person', 'A Tree', 'A Pencil'], correctAnswer: 'A Candle' },
    { id: 'riddle-22', question: 'What has to be broken before you can use it?', options: ['An Egg', 'A Glowstick', 'A Promise', 'A Record'], correctAnswer: 'An Egg' },
    { id: 'riddle-23', question: 'What goes up but never comes down?', options: ['Age', 'Rain', 'Smoke', 'Balloon'], correctAnswer: 'Age' },
    { id: 'riddle-24', question: 'A man rides into town on Friday, stays for three days and leaves on Friday. How is this possible?', options: ['His horse is named Friday', 'He used a time machine', 'He stayed for a week', 'It was a short visit'], correctAnswer: 'His horse is named Friday' },
    { id: 'riddle-25', question: 'I follow you all the time and copy your every move, but you can\'t touch me or catch me. What am I?', options: ['Your Shadow', 'Your Reflection', 'A Stalker', 'Your Echo'], correctAnswer: 'Your Shadow' },
    { id: 'riddle-26', question: 'What has one eye but can\'t see?', options: ['A Needle', 'A Storm', 'A Potato', 'A Cyclops'], correctAnswer: 'A Needle' },
    { id: 'riddle-27', question: 'What has many keys but can\'t open a single lock?', options: ['A Piano', 'A Map', 'A Keychain', 'A Crypt'], correctAnswer: 'A Piano' },
    { id: 'riddle-28', question: 'What can hold a lot of water but has no mouth?', options: ['A Sponge', 'A Bucket', 'A Lake', 'A Cloud'], correctAnswer: 'A Sponge' },
    { id: 'riddle-29', question: 'What has teeth but cannot bite?', options: ['A Comb', 'A Saw', 'A Zipper', 'A Gear'], correctAnswer: 'A Comb' },
    { id: 'riddle-30', question: 'What has words, but never speaks?', options: ['A Book', 'A Person', 'A Recording', 'A Letter'], correctAnswer: 'A Book' },
    { id: 'riddle-31', question: 'What runs all around a backyard, yet never moves?', options: ['A Fence', 'A Dog', 'Grass', 'Wind'], correctAnswer: 'A Fence' },
    { id: 'riddle-32', question: 'What can travel all around the world without leaving its corner?', options: ['A Stamp', 'A Globe', 'The Moon', 'A Thought'], correctAnswer: 'A Stamp' },
    { id: 'riddle-33', question: 'What has a thumb and four fingers, but is not hand?', options: ['A Glove', 'A Foot', 'A Monkey', 'A Claw'], correctAnswer: 'A Glove' },
    { id: 'riddle-34', question: 'What has a head and a foot but no body?', options: ['A Bed', 'A Coin', 'A Mountain', 'A River'], correctAnswer: 'A Bed' },
    { id: 'riddle-35', question: 'Where does one wall meet the other wall?', options: ['In the Corner', 'On the Ceiling', 'On the Floor', 'At the Door'], correctAnswer: 'In the Corner' },
    { id: 'riddle-36', question: 'What building has the most stories?', options: ['The Library', 'A Skyscraper', 'A Hotel', 'A School'], correctAnswer: 'The Library' },
    { id: 'riddle-37', question: 'What tastes better than it smells?', options: ['A Tongue', 'Medicine', 'Water', 'Salt'], correctAnswer: 'A Tongue' },
    { id: 'riddle-38', question: 'What has 13 hearts, but no other organs?', options: ['A Deck of Cards', 'A Monster', 'A Hospital', 'A Bouquet'], correctAnswer: 'A Deck of Cards' },
    { id: 'riddle-39', question: 'It belongs to you, but other people use it more than you do. What is it?', options: ['Your Name', 'Your Money', 'Your Car', 'Your Patience'], correctAnswer: 'Your Name' },
    { id: 'riddle-40', question: 'I have mountains without stone, lakes without water, cities without buildings. What am I?', options: ['A Map', 'A Dream', 'A Globe', 'A Painting'], correctAnswer: 'A Map' },
    { id: 'riddle-41', question: 'What has hands but cannot clap?', options: ['A Clock', 'A Statue', 'A Doll', 'A Tree'], correctAnswer: 'A Clock' },
    { id: 'riddle-42', question: 'What can you catch, but not throw?', options: ['A Cold', 'A Ball', 'A Fish', 'A Boomerang'], correctAnswer: 'A Cold' },
    { id: 'riddle-43', question: 'I am an odd number. Take away a letter and I become even. What number am I?', options: ['Seven', 'Eleven', 'Three', 'Nine'], correctAnswer: 'Seven' },
    { id: 'riddle-44', question: 'If you drop me I\'m sure to crack, but give me a smile and I\'ll always smile back. What am I?', options: ['A Mirror', 'An Egg', 'A Plate', 'A Glass'], correctAnswer: 'A Mirror' },
    { id: 'riddle-45', question: 'What goes through cities and fields, but never moves?', options: ['A Road', 'A River', 'Wind', 'Light'], correctAnswer: 'A Road' },
    { id: 'riddle-46', question: 'I am always hungry, I must always be fed. The finger I lick will soon turn red. What am I?', options: ['Fire', 'A Baby', 'A Vampire', 'A Stove'], correctAnswer: 'Fire' },
    { id: 'riddle-47', question: 'The person who makes it has no need of it; the person who buys it has no use for it. The person who uses it can neither see nor feel it. What is it?', options: ['A Coffin', 'A Gift', 'A Bed', 'A Shoe'], correctAnswer: 'A Coffin' },
    { id: 'riddle-48', question: 'I have lakes with no water, mountains with no stone and cities with no buildings. What am I?', options: ['A Map', 'A Desert', 'A Drawing', 'A Planet'], correctAnswer: 'A Map' },
    { id: 'riddle-49', question: 'What has four legs in the morning, two legs in the afternoon, and three legs in the evening?', options: ['A Human', 'A Table', 'A Horse', 'A Chair'], correctAnswer: 'A Human' },
    { id: 'riddle-50', question: 'I come from a mine and get surrounded by wood. Everyone uses me. What am I?', options: ['Pencil Lead', 'Coal', 'Diamond', 'Iron'], correctAnswer: 'Pencil Lead' },
    { id: 'riddle-51', question: 'I am not alive, but I grow; I don\'t have lungs, but I need air; I don\'t have a mouth, but water kills me. What am I?', options: ['Fire', 'A Plant', 'A Balloon', 'Ice'], correctAnswer: 'Fire' },
    { id: 'riddle-52', question: 'What has a single eye but cannot see?', options: ['A Needle', 'A Storm', 'A Potato', 'A Cyclops'], correctAnswer: 'A Needle' },
    { id: 'riddle-53', question: 'What has many needles, but doesn\'t sew?', options: ['A Christmas Tree', 'A Doctor', 'A Porcupine', 'A Cactus'], correctAnswer: 'A Christmas Tree' },
    { id: 'riddle-54', question: 'What has legs, but doesn\'t walk?', options: ['A Table', 'A Dog', 'A Snake', 'A Car'], correctAnswer: 'A Table' },
    { id: 'riddle-55', question: 'What kind of room has no doors or windows?', options: ['A Mushroom', 'A Ballroom', 'A Chatroom', 'A Courtroom'], correctAnswer: 'A Mushroom' },
    { id: 'riddle-56', question: 'What begins with an E but only has one letter?', options: ['Envelope', 'Eye', 'Engine', 'Egg'], correctAnswer: 'Envelope' },
    { id: 'riddle-57', question: 'I am full of holes, but I can hold water. What am I?', options: ['A Sponge', 'A Net', 'A Bucket', 'A Strainer'], correctAnswer: 'A Sponge' },
    { id: 'riddle-58', question: 'What is always in front of you but can\'t be seen?', options: ['The Future', 'Air', 'Your Nose', 'Glass'], correctAnswer: 'The Future' },
    { id: 'riddle-59', question: 'There is a house. One enters it blind and comes out seeing. What is it?', options: ['A School', 'A Hospital', 'A Cinema', 'A Library'], correctAnswer: 'A School' },
    { id: 'riddle-60', question: 'What can you break, even if you never pick it up or touch it?', options: ['A Promise', 'The Law', 'A Heart', 'Silence'], correctAnswer: 'A Promise' },
    { id: 'riddle-61', question: 'What goes up but never comes down?', options: ['Your Age', 'A Balloon', 'Smoke', 'Heat'], correctAnswer: 'Your Age' },
    { id: 'riddle-62', question: 'You can hold me in your left hand, but not in your right hand. What am I?', options: ['Your Right Elbow', 'A Ball', 'Your Left Elbow', 'Air'], correctAnswer: 'Your Right Elbow' },
    { id: 'riddle-63', question: 'What is 3/7 chicken, 2/3 cat and 2/4 goat?', options: ['Chicago', 'Chimera', 'Cattle', 'Ghost'], correctAnswer: 'Chicago' },
    { id: 'riddle-64', question: 'I have three eyes, all in a row; when the red one opens, all freeze.', options: ['Traffic Light', 'Monster', 'Camera', 'Alien'], correctAnswer: 'Traffic Light' },
    { id: 'riddle-65', question: 'What never asks questions but is often answered?', options: ['A Doorbell', 'A Teacher', 'A Riddle', 'A Phone'], correctAnswer: 'A Doorbell' },
    { id: 'riddle-66', question: 'What belongs to you but is used more by others?', options: ['Your Name', 'Your Car', 'Your House', 'Your Money'], correctAnswer: 'Your Name' },
    { id: 'riddle-67', question: 'I\'m light as a feather, yet the strongest man can\'t hold me for much more than a minute. What am I?', options: ['Breath', 'A Bubble', 'A Thought', 'Smoke'], correctAnswer: 'Breath' },
    { id: 'riddle-68', question: 'What goes up and down but doesn\'t move?', options: ['Stairs', 'Elevator', 'Temperature', 'Price'], correctAnswer: 'Stairs' },
    { id: 'riddle-69', question: 'Which month has 28 days?', options: ['All of them', 'February', 'January', 'December'], correctAnswer: 'All of them' },
    { id: 'riddle-70', question: 'Where is the only place where today comes before yesterday?', options: ['Dictionary', 'Calendar', 'History Book', 'Timeline'], correctAnswer: 'Dictionary' },
    { id: 'riddle-71', question: 'What has one head, one foot and four legs?', options: ['A Bed', 'A Dog', 'A Person', 'A Table'], correctAnswer: 'A Bed' },
    { id: 'riddle-72', question: 'What can\'t be used until it\'s broken?', options: ['An Egg', 'A Glowstick', 'A Pinata', 'A Coconut'], correctAnswer: 'An Egg' },
    { id: 'riddle-73', question: 'What has many teeth, but can\'t bite?', options: ['A Comb', 'A Saw', 'A Zipper', 'A Gear'], correctAnswer: 'A Comb' },
    { id: 'riddle-74', question: 'What has words, but never speaks?', options: ['A Book', 'A Letter', 'A Sign', 'A Song'], correctAnswer: 'A Book' },
    { id: 'riddle-75', question: 'What runs all around a backyard, yet never moves?', options: ['A Fence', 'A Dog', 'Leaves', 'Wind'], correctAnswer: 'A Fence' },
    { id: 'riddle-76', question: 'What can travel all around the world without leaving its corner?', options: ['A Stamp', 'The Moon', 'A Satellite', 'A Thought'], correctAnswer: 'A Stamp' },
    { id: 'riddle-77', question: 'What has a thumb and four fingers, but is not hand?', options: ['A Glove', 'A Foot', 'A Robot', 'A Drawing'], correctAnswer: 'A Glove' },
    { id: 'riddle-78', question: 'What has a head and a tail but no body?', options: ['A Coin', 'A Serpent', 'A Comet', 'A Story'], correctAnswer: 'A Coin' },
    { id: 'riddle-79', question: 'Where does one wall meet the other wall?', options: ['In the Corner', 'At the Door', 'On the Floor', 'On the Ceiling'], correctAnswer: 'In the Corner' },
    { id: 'riddle-80', question: 'What building has the most stories?', options: ['The Library', 'A Tower', 'A Skyscraper', 'A Hotel'], correctAnswer: 'The Library' },
    { id: 'riddle-81', question: 'What tastes better than it smells?', options: ['A Tongue', 'Water', 'Medicine', 'Soup'], correctAnswer: 'A Tongue' },
    { id: 'riddle-82', question: 'What has 13 hearts, but no other organs?', options: ['A Deck of Cards', 'A Monster', 'A Hospital', 'A Romance Novel'], correctAnswer: 'A Deck of Cards' },
    { id: 'riddle-83', question: 'It belongs to you, but other people use it more than you do. What is it?', options: ['Your Name', 'Your Patience', 'Your Advice', 'Your Time'], correctAnswer: 'Your Name' },
    { id: 'riddle-84', question: 'I have mountains without stone, lakes without water, cities without buildings. What am I?', options: ['A Map', 'A Dream', 'A Drawing', 'A Globe'], correctAnswer: 'A Map' },
    { id: 'riddle-85', question: 'What has hands but cannot clap?', options: ['A Clock', 'A Statue', 'A Doll', 'A Tree'], correctAnswer: 'A Clock' },
    { id: 'riddle-86', question: 'What can you catch, but not throw?', options: ['A Cold', 'A Train', 'A Ball', 'A Hint'], correctAnswer: 'A Cold' },
    { id: 'riddle-87', question: 'I am an odd number. Take away a letter and I become even. What number am I?', options: ['Seven', 'Eleven', 'Nine', 'One'], correctAnswer: 'Seven' },
    { id: 'riddle-88', question: 'If you drop me I\'m sure to crack, but give me a smile and I\'ll always smile back. What am I?', options: ['A Mirror', 'An Egg', 'A Glass', 'A Nut'], correctAnswer: 'A Mirror' },
    { id: 'riddle-89', question: 'What goes through cities and fields, but never moves?', options: ['A Road', 'A River', 'A Fence', 'A Power Line'], correctAnswer: 'A Road' },
    { id: 'riddle-90', question: 'I am always hungry, I must always be fed. The finger I lick will soon turn red. What am I?', options: ['Fire', 'A Baby', 'A Mosquito', 'A Vampire'], correctAnswer: 'Fire' },
    { id: 'riddle-91', question: 'The person who makes it has no need of it; the person who buys it has no use for it. The person who uses it can neither see nor feel it. What is it?', options: ['A Coffin', 'A Gift', 'A Bed', 'A Trap'], correctAnswer: 'A Coffin' },
    { id: 'riddle-92', question: 'I have lakes with no water, mountains with no stone and cities with no buildings. What am I?', options: ['A Map', 'A Desert', 'A Picture', 'A Planet'], correctAnswer: 'A Map' },
    { id: 'riddle-93', question: 'What has four legs in the morning, two legs in the afternoon, and three legs in the evening?', options: ['A Human', 'A Table', 'A Horse', 'A Chair'], correctAnswer: 'A Human' },
    { id: 'riddle-94', question: 'I come from a mine and get surrounded by wood. Everyone uses me. What am I?', options: ['Pencil Lead', 'Coal', 'Diamond', 'Gold'], correctAnswer: 'Pencil Lead' },
    { id: 'riddle-95', question: 'I am not alive, but I grow; I don\'t have lungs, but I need air; I don\'t have a mouth, but water kills me. What am I?', options: ['Fire', 'A Plant', 'A Crystal', 'Mold'], correctAnswer: 'Fire' },
    { id: 'riddle-96', question: 'What has a single eye but cannot see?', options: ['A Needle', 'A Storm', 'A Cyclops', 'A Camera'], correctAnswer: 'A Needle' },
    { id: 'riddle-97', question: 'What has many needles, but doesn\'t sew?', options: ['A Christmas Tree', 'A Porcupine', 'A Doctor', 'A Cactus'], correctAnswer: 'A Christmas Tree' },
    { id: 'riddle-98', question: 'What has legs, but doesn\'t walk?', options: ['A Table', 'A Chair', 'A Bed', 'Pants'], correctAnswer: 'A Table' },
    { id: 'riddle-99', question: 'What kind of room has no doors or windows?', options: ['A Mushroom', 'A Chatroom', 'A Courtroom', 'Elbow Room'], correctAnswer: 'A Mushroom' },
    { id: 'riddle-100', question: 'What begins with an E but only has one letter?', options: ['Envelope', 'Eye', 'End', 'Earth'], correctAnswer: 'Envelope' }
];
