export interface RiddleDefinition {
    id: string;
    question: string;
    options: string[]; // First 4 options are used, shuffling is handled by the consumer
    correctAnswer: string;
}

export const RIDDLE_DATA: RiddleDefinition[] = [
    { id: 'riddle-1', question: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?', options: ['An echo', 'A ghost', 'A cloud', 'A whisper'], correctAnswer: 'An echo' },
    { id: 'riddle-2', question: 'The more of this there is, the less you see. What is it?', options: ['Darkness', 'Fog', 'Light', 'Smoke'], correctAnswer: 'Darkness' },
    { id: 'riddle-3', question: 'I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?', options: ['A map', 'A globe', 'A painting', 'A book'], correctAnswer: 'A map' },
    { id: 'riddle-4', question: 'What has keys, but no locks; space, but no room; and you can enter, but not go in?', options: ['A keyboard', 'A piano', 'A computer', 'A castle'], correctAnswer: 'A keyboard' },
    { id: 'riddle-5', question: 'I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by everyone. What am I?', options: ['Pencil lead', 'Coal', 'Diamond', 'Gold'], correctAnswer: 'Pencil lead' },
    { id: 'riddle-6', question: 'What is so fragile that saying its name breaks it?', options: ['Silence', 'Glass', 'A secret', 'A promise'], correctAnswer: 'Silence' },
    { id: 'riddle-7', question: 'The more you take, the more you leave behind. What are they?', options: ['Footsteps', 'Fingerprints', 'Memories', 'Time'], correctAnswer: 'Footsteps' },
    { id: 'riddle-8', question: 'What has a face and two hands but no arms or legs?', options: ['A clock', 'A watch', 'A statue', 'A puppet'], correctAnswer: 'A clock' },
    { id: 'riddle-9', question: 'What gets wetter as it dries?', options: ['A towel', 'A sponge', 'A cloud', 'Steam'], correctAnswer: 'A towel' },
    { id: 'riddle-10', question: 'What has a neck but no head?', options: ['A bottle', 'A shirt', 'A guitar', 'A vase'], correctAnswer: 'A bottle' },
    { id: 'riddle-11', question: 'I am always coming, but never arrive. What am I?', options: ['Tomorrow', 'The train', 'The season', 'A dream'], correctAnswer: 'Tomorrow' },
    { id: 'riddle-12', question: 'What can be broken, but is never held in your hands?', options: ['A promise', 'A mirror', 'A crystal', 'A chain'], correctAnswer: 'A promise' },
    { id: 'riddle-13', question: 'I have branches, but no fruit, trunk or leaves. What am I?', options: ['A bank', 'A library', 'A cavern', 'A vine'], correctAnswer: 'A bank' },
    { id: 'riddle-14', question: 'Feed me and I live, yet give me a drink and I die. What am I?', options: ['Fire', 'A campfire', 'Thirst', 'Hunger'], correctAnswer: 'Fire' },
    { id: 'riddle-15', question: 'What is light as a feather, but even the strongest hero cannot hold it for five minutes?', options: ['Breath', 'Smoke', 'A bubble', 'A whisper'], correctAnswer: 'Breath' },
    { id: 'riddle-16', question: 'What has a head and a tail but no body?', options: ['A coin', 'A comet', 'A lizard', 'A needle'], correctAnswer: 'A coin' },
    { id: 'riddle-17', question: 'What comes once in a minute, twice in a moment, but never in a thousand years?', options: ['The letter M', 'A leap year', 'A comet', 'A solar eclipse'], correctAnswer: 'The letter M' },
    { id: 'riddle-18', question: 'I have holes on top and bottom, left and right, yet I hold water without spilling. What am I?', options: ['A sponge', 'A sieve', 'A barrel', 'A pipe'], correctAnswer: 'A sponge' },
    { id: 'riddle-19', question: 'If you have me, you want to share me. If you share me, you no longer possess me. What am I?', options: ['A secret', 'Gold', 'Wisdom', 'Bread'], correctAnswer: 'A secret' },
    { id: 'riddle-20', question: 'What starts with T, ends with T, and has T in it?', options: ['A teapot', 'A tent', 'A target', 'A torrent'], correctAnswer: 'A teapot' },
    { id: 'riddle-21', question: 'I am tall when young, and short when old. What am I?', options: ['A candle', 'A sapling', 'A shadow', 'A tower'], correctAnswer: 'A candle' },
    { id: 'riddle-22', question: 'What has to be cracked open before you can use it?', options: ['An egg', 'A walnut', 'A geode', 'A chest'], correctAnswer: 'An egg' },
    { id: 'riddle-23', question: 'What goes up every single year but never comes down?', options: ['Your age', 'A balloon', 'Smoke', 'The tide'], correctAnswer: 'Your age' },
    { id: 'riddle-24', question: 'I follow you everywhere in the light, but vanish the moment darkness falls. What am I?', options: ['Your shadow', 'Your reflection', 'A ghost', 'Your cloak'], correctAnswer: 'Your shadow' },
    { id: 'riddle-25', question: 'What has one sharp eye but cannot see a single thing?', options: ['A needle', 'A storm', 'A hurricane', 'A potato'], correctAnswer: 'A needle' },
    { id: 'riddle-26', question: 'What has eighty-eight keys but cannot open a single door in the castle?', options: ['A piano', 'A keychain', 'A harp', 'A lockbox'], correctAnswer: 'A piano' },
    { id: 'riddle-27', question: 'What has many fine teeth but cannot chew a morsel of food?', options: ['A comb', 'A saw', 'A zipper', 'A gear'], correctAnswer: 'A comb' },
    { id: 'riddle-28', question: 'What has thousands of words, but never speaks a sound?', options: ['A book', 'A scroll', 'A wall', 'A monument'], correctAnswer: 'A book' },
    { id: 'riddle-29', question: 'What runs around the entire perimeter of a fortress, yet never takes a step?', options: ['A fence', 'A guard', 'A moat', 'A road'], correctAnswer: 'A fence' },
    { id: 'riddle-30', question: 'What can travel to the four corners of the earth while remaining in one corner?', options: ['A postage stamp', 'A compass', 'A flag', 'A raven'], correctAnswer: 'A postage stamp' },
    { id: 'riddle-31', question: 'What has a thumb and four fingers, but is not alive and has no flesh?', options: ['A glove', 'A gauntlet', 'A mitten', 'A puppet'], correctAnswer: 'A glove' },
    { id: 'riddle-32', question: 'What has a head and a foot, but neither legs nor a torso?', options: ['A bed', 'A coin', 'A mountain', 'A nail'], correctAnswer: 'A bed' },
    { id: 'riddle-33', question: 'What building in the kingdom contains the greatest number of stories?', options: ['The library', 'The citadel', 'The cathedral', 'The tavern'], correctAnswer: 'The library' },
    { id: 'riddle-34', question: 'What organ tastes significantly better than it smells?', options: ['A tongue', 'An ear', 'A nose', 'A throat'], correctAnswer: 'A tongue' },
    { id: 'riddle-35', question: 'What has thirteen hearts, yet neither lungs nor blood?', options: ['A deck of cards', 'A chimera', 'An artichoke', 'A tapestry'], correctAnswer: 'A deck of cards' },
    { id: 'riddle-36', question: 'It belongs strictly to you, but everyone else in the realm uses it far more often. What is it?', options: ['Your name', 'Your gold', 'Your mirror', 'Your horse'], correctAnswer: 'Your name' },
    { id: 'riddle-37', question: 'What can you catch on a chilly evening, but can never toss or throw?', options: ['A cold', 'A whisper', 'A star', 'A snowflake'], correctAnswer: 'A cold' },
    { id: 'riddle-38', question: 'I am an odd number. Strip away my first letter and I become even. What number am I?', options: ['Seven', 'Eleven', 'Nine', 'Three'], correctAnswer: 'Seven' },
    { id: 'riddle-39', question: 'If you drop me I crack and shatter, but give me a grin and I smile right back. What am I?', options: ['A mirror', 'A porcelain cup', 'A glass window', 'A puddle'], correctAnswer: 'A mirror' },
    { id: 'riddle-40', question: 'What paved ribbon stretches across mountains and valleys without ever moving an inch?', options: ['A road', 'A river', 'A pipeline', 'A bridge'], correctAnswer: 'A road' },
    { id: 'riddle-41', question: 'The builder has no use for it, the buyer never sleeps in it, and the occupant never knows they are in it. What is it?', options: ['A coffin', 'A cradle', 'A prison cell', 'A trapdoor'], correctAnswer: 'A coffin' },
    { id: 'riddle-42', question: 'What walks on four legs at dawn, two legs at midday, and three legs at sunset?', options: ['A human', 'A sphinx', 'A quadruped', 'A hound'], correctAnswer: 'A human' },
    { id: 'riddle-43', question: 'What has many sharp needles on its branches, but has never sewn a coat?', options: ['A pine tree', 'A porcupine', 'A hedgehog', 'A cactus'], correctAnswer: 'A pine tree' },
    { id: 'riddle-44', question: 'What has four legs, but cannot walk or move by itself?', options: ['A table', 'A centipede', 'A carriage', 'A saddle'], correctAnswer: 'A table' },
    { id: 'riddle-45', question: 'What kind of room has neither doors nor windows, yet grows in dark damp soil?', options: ['A mushroom', 'A root cellar', 'A dungeon', 'A cavern'], correctAnswer: 'A mushroom' },
    { id: 'riddle-46', question: 'What begins with an E, ends with an E, but holds only one single letter?', options: ['An envelope', 'An eye', 'An empire', 'An eagle'], correctAnswer: 'An envelope' },
    { id: 'riddle-47', question: 'I am not alive, but I grow. I have no lungs, but I breathe air. Water drowns me in seconds. What am I?', options: ['A campfire', 'A vine', 'A crystal', 'A tempest'], correctAnswer: 'A campfire' },
    { id: 'riddle-48', question: 'I have a spine, but no bones inside. I have leaves, but no branches or bark. What am I?', options: ['A book', 'A palm tree', 'A quill', 'A fern'], correctAnswer: 'A book' },
    { id: 'riddle-49', question: 'What has a ring, but no finger to wear it on?', options: ['A telephone', 'A bell', 'A tree stump', 'A circus'], correctAnswer: 'A telephone' },
    { id: 'riddle-50', question: 'I fly without wings, I weep without eyes. Whenever I arrive, darkness flies across the sky. What am I?', options: ['A cloud', 'The wind', 'Nightfall', 'A shadow'], correctAnswer: 'A cloud' },
    { id: 'riddle-51', question: 'I have no flesh, feathers, scales, or bone, yet I possess two fingers and two thumbs. What am I?', options: ['A pair of gloves', 'A marionette', 'A stone carving', 'A crab claw'], correctAnswer: 'A pair of gloves' },
    { id: 'riddle-52', question: 'What can fill an entire grand banquet hall without taking up a single speck of room?', options: ['Light', 'Smoke', 'Air', 'Laughter'], correctAnswer: 'Light' },
    { id: 'riddle-53', question: 'I am always hungry; give me wood and I roar, give me water and I gasp my last breath. What am I?', options: ['A blaze', 'A monster', 'A furnace', 'A drought'], correctAnswer: 'A blaze' },
    { id: 'riddle-54', question: 'What runs all day long, has a bed but never sleeps, and has a mouth but never speaks?', options: ['A river', 'A clock', 'A wagon', 'A windmill'], correctAnswer: 'A river' },
    { id: 'riddle-55', question: 'What can you hear, but never see or hold, and it never speaks until spoken to?', options: ['An echo', 'The wind', 'A chime', 'A thought'], correctAnswer: 'An echo' },
    { id: 'riddle-56', question: 'The person who makes me sells me. The person who buys me never uses me. What am I?', options: ['A tombstone', 'A saddle', 'A sword', 'A carriage'], correctAnswer: 'A tombstone' },
    { id: 'riddle-57', question: 'What loses its head in the morning and gets it back every night?', options: ['A pillow', 'A night watchman', 'A candle', 'The moon'], correctAnswer: 'A pillow' },
    { id: 'riddle-58', question: 'What has bark, but cannot bite or make a sound?', options: ['A tree', 'A dog', 'A sailing ship', 'A seal'], correctAnswer: 'A tree' },
    { id: 'riddle-59', question: 'What has no feet, no hands, and no wings, but climbs toward the heavens?', options: ['Smoke', 'A vine', 'A beanstalk', 'Mist'], correctAnswer: 'Smoke' },
    { id: 'riddle-60', question: 'I have a heart that doesn’t beat, and I live in an orchard. What am I?', options: ['An artichoke', 'An apple', 'A walnut', 'A palm'], correctAnswer: 'An artichoke' },
    { id: 'riddle-61', question: 'What kind of band never plays an instrument or sings a ballad?', options: ['A rubber band', 'A guild band', 'A march', 'An archer band'], correctAnswer: 'A rubber band' },
    { id: 'riddle-62', question: 'What has an eye in its middle, but can see neither land nor sky?', options: ['A storm', 'A hurricane', 'A needle', 'A target'], correctAnswer: 'A hurricane' },
    { id: 'riddle-63', question: 'I shave every single day across the village, yet my beard remains exactly the same length. Who am I?', options: ['A barber', 'A wizard', 'A hermit', 'A sheep'], correctAnswer: 'A barber' },
    { id: 'riddle-64', question: 'What begins with T, finishes with T, and contains hot tea?', options: ['A teapot', 'A kettle', 'A teacup', 'A thermos'], correctAnswer: 'A teapot' },
    { id: 'riddle-65', question: 'You see a boat filled with people. It capsizes, yet not a single person got wet. How?', options: ['Everyone was married', 'It was a submarine', 'It happened in winter', 'They were ghosts'], correctAnswer: 'Everyone was married' },
    { id: 'riddle-66', question: 'What has a golden horn, but never blows a trumpet call?', options: ['A crescent moon', 'A unicorn', 'A ram', 'A stag'], correctAnswer: 'A crescent moon' },
    { id: 'riddle-67', question: 'What is always found in the past, present in the present, but missing from tomorrow?', options: ['The letter P', 'Memories', 'Yesterday', 'History'], correctAnswer: 'The letter P' },
    { id: 'riddle-68', question: 'What gets sharper the more you use your mind on it?', options: ['Wit', 'A whetstone', 'A rapier', 'A quill'], correctAnswer: 'Wit' },
    { id: 'riddle-69', question: 'I have eighty-eight keys that sing, but not one can turn a bolt or open a chest. What am I?', options: ['A harpsichord', 'A piano', 'An organ', 'A chime'], correctAnswer: 'A piano' },
    { id: 'riddle-70', question: 'What is full of holes, yet can hold pure water from a mountain spring?', options: ['A sponge', 'A fishing net', 'A sieve', 'A funnel'], correctAnswer: 'A sponge' },
    { id: 'riddle-71', question: 'What holds water inside it even though it is carved from stone and stands upside down?', options: ['A cavern stalactite', 'A well', 'A stone font', 'A cistern'], correctAnswer: 'A stone font' },
    { id: 'riddle-72', question: 'I have no voice, but I shout warnings of danger across the rocks. What am I?', options: ['A lighthouse', 'A flare', 'A watch bell', 'A beacon'], correctAnswer: 'A lighthouse' },
    { id: 'riddle-73', question: 'What comes down from the clouds but never climbs back up by itself?', options: ['Rain', 'Hail', 'Snow', 'Fog'], correctAnswer: 'Rain' },
    { id: 'riddle-74', question: 'What has teeth from end to end, but neither tongue nor gums to swallow food?', options: ['A saw', 'A rake', 'A comb', 'A gear'], correctAnswer: 'A saw' },
    { id: 'riddle-75', question: 'What has hands that move in circles, but never touches anything around it?', options: ['A sundial', 'A compass', 'A windmill', 'A clock'], correctAnswer: 'A sundial' },
    { id: 'riddle-76', question: 'What has a crown, but is neither king nor queen?', options: ['A tree', 'A tooth', 'A pineapple', 'A mountain peak'], correctAnswer: 'A pineapple' },
    { id: 'riddle-77', question: 'What can be heard in the woods, seen on the water, and felt in the wind, but cannot be caught?', options: ['A ripple', 'An echo', 'A breeze', 'A ray of sun'], correctAnswer: 'A ripple' },
    { id: 'riddle-78', question: 'I am wrapped in green armor in summer, golden armor in autumn, and naked in winter. What am I?', options: ['A deciduous tree', 'An oak', 'A vine', 'A willow'], correctAnswer: 'A deciduous tree' },
    { id: 'riddle-79', question: 'What travels beneath bridges, through valleys, and around castles without legs?', options: ['A river', 'A mist', 'A shadow', 'A cart'], correctAnswer: 'A river' },
    { id: 'riddle-80', question: 'What is always moving forward, yet leaves no trail in the mud?', options: ['Time', 'The wind', 'A shadow', 'A ghost'], correctAnswer: 'Time' },
    { id: 'riddle-81', question: 'What can pierce stone without making a hole, and cross water without sinking?', options: ['Sunlight', 'A shadow', 'A whisper', 'A thought'], correctAnswer: 'Sunlight' },
    { id: 'riddle-82', question: 'I am born high in the mountains, run all my life to the sea, and never stop for rest. What am I?', options: ['A river stream', 'A glacier', 'A waterfall', 'An avalanche'], correctAnswer: 'A river stream' },
    { id: 'riddle-83', question: 'What has an iron tongue that only rings when struck with force?', options: ['A church bell', 'An anvil', 'A shield', 'A chime'], correctAnswer: 'A church bell' },
    { id: 'riddle-84', question: 'What has five petals in the sun, blooms in the frost, and melts in your palm?', options: ['A snowflake', 'An ice lily', 'A hailstone', 'Morning frost'], correctAnswer: 'A snowflake' },
    { id: 'riddle-85', question: 'What has a bow but shoots no arrows, and bridges two kingdoms across the clouds?', options: ['A rainbow', 'A violin bow', 'An archway', 'A ribbon'], correctAnswer: 'A rainbow' },
    { id: 'riddle-86', question: 'What has wings but cannot soar, runs fast across the sands, and buries its head in fear?', options: ['An ostrich', 'A penguin', 'An emu', 'A peacock'], correctAnswer: 'An ostrich' },
    { id: 'riddle-87', question: 'What can fill a room with beauty without moving a single stone or chair?', options: ['Music', 'Perfume', 'Laughter', 'Warmth'], correctAnswer: 'Music' },
    { id: 'riddle-88', question: 'I have a crust, but no bread. I have a mantle, but wear no cloak. What am I?', options: ['The earth', 'A pie', 'A volcano', 'A tortoise'], correctAnswer: 'The earth' },
    { id: 'riddle-89', question: 'What can leap over a castle wall without bending its knees?', options: ['A cannonball', 'The wind', 'A shadow', 'A falcon'], correctAnswer: 'A cannonball' },
    { id: 'riddle-90', question: 'What grows downward into darkness while reaching for subterranean springs?', options: ['A tree root', 'An icicle', 'A stalactite', 'A miner'], correctAnswer: 'A tree root' },
    { id: 'riddle-91', question: 'What wears a coat in winter and sheds it when the warm sun arrives?', options: ['A sheep', 'A bear', 'A serpent', 'A horse'], correctAnswer: 'A sheep' },
    { id: 'riddle-92', question: 'What has four legs, a broad back, and carries riders through cobblestone streets?', options: ['A horse', 'A donkey', 'A camel', 'A mule'], correctAnswer: 'A horse' },
    { id: 'riddle-93', question: 'I fly through the night without wings or feathers, guided only by the stars. What am I?', options: ['A shooting star', 'A bat', 'An owl', 'A comet'], correctAnswer: 'A comet' },
    { id: 'riddle-94', question: 'What has three needles, spins in circles, and measures our most precious treasure?', options: ['A clock', 'A compass', 'A loom', 'A spinning wheel'], correctAnswer: 'A clock' },
    { id: 'riddle-95', question: 'What can be given away without losing it, and makes both giver and receiver wealthy?', options: ['Kindness', 'Gold', 'Advice', 'Knowledge'], correctAnswer: 'Kindness' },
    { id: 'riddle-96', question: 'What has a needle that always points toward the cold north wind?', options: ['A compass', 'A sundial', 'A weather vane', 'A magnet'], correctAnswer: 'A compass' },
    { id: 'riddle-97', question: 'What sleeps in a sheath by day and awakens with steel sparks in battle?', options: ['A sword', 'A dagger', 'An arrow', 'A spear'], correctAnswer: 'A sword' },
    { id: 'riddle-98', question: 'What is woven without a loom, catches dew at dawn, and snares unwary flies?', options: ['A spider web', 'A fishing net', 'A silk cloak', 'A hammock'], correctAnswer: 'A spider web' },
    { id: 'riddle-99', question: 'What has a shell that holds no snail, but hides a golden sun inside white clouds?', options: ['An egg', 'A clam', 'A coconut', 'A walnut'], correctAnswer: 'An egg' },
    { id: 'riddle-100', question: 'What is always in front of you, guiding your every choice, yet can never be seen until lived?', options: ['The future', 'Your nose', 'Your destiny', 'A horizon'], correctAnswer: 'The future' }
];
