import { TileType } from '@/types/tiles';

export function getTileName(type: TileType): string {
  const tileNames: Record<TileType, string> = {
    empty: 'Empty',
    grass: 'Grass',
    water: 'Water',
    mountain: 'Mountain',
    forest: 'Forest',
    city: 'City',
    town: 'Town',
    dungeon: 'Dungeon',
    castle: 'Castle',
    special: 'Special',
    snow: 'Snow',
    desert: 'Desert',
    ice: 'Ice',
    lava: 'Lava',
    swamp: 'Swamp',
    mystery: 'Mystery',
    treasure: 'Treasure',
    monster: 'Monster',
    'portal-entrance': 'Portal Entrance',
    'portal-exit': 'Portal Exit',
    cave: 'Cave',
    volcano: 'Volcano',
    sheep: 'Sheep',
    horse: 'Horse',
    vacant: 'Vacant',
    // Property tiles
    archery: 'Archery',
    blacksmith: 'Blacksmith',
    sawmill: 'Sawmill',
    fisherman: 'Fisherman',
    grocery: 'Grocery',
    foodcourt: 'Food Court',
    well: 'Well',
    windmill: 'Windmill',
    fountain: 'Fountain',
    house: 'House',
    inn: 'Inn',
    jousting: 'Jousting',
    mansion: 'Mansion',
    mayor: 'Mayor',
    'streak-scroll': 'Streak Scroll',
    farm: 'Farm',
    lumber_mill: 'Lumber Mill',
    market: 'Market',
    cottage: 'Cottage',
    crossroad: 'Crossroad',
    straightroad: 'Straight Road',
  };
  return tileNames[type] || 'Unknown';
}

export function getDefaultConnections(type: TileType): string[] {
  const defaultConnections: Record<TileType, string[]> = {
    empty: [],
    grass: ['grass', 'town', 'city', 'castle', 'dungeon'],
    water: ['water'],
    mountain: ['mountain', 'dungeon'],
    forest: ['forest', 'dungeon'],
    city: ['grass'],
    town: ['grass'],
    dungeon: ['mountain', 'forest', 'grass'],
    castle: ['grass'],
    special: [],
    snow: [],
    desert: [],
    ice: [],
    lava: [],
    swamp: [],
    mystery: [],
    treasure: [],
    monster: [],
    'portal-entrance': [],
    'portal-exit': [],
    cave: ['mountain', 'grass'],
    volcano: ['lava', 'mountain'],
    sheep: ['grass'],
    horse: ['grass'],
    vacant: [],
    // Property tiles
    archery: ['grass'],
    blacksmith: ['grass'],
    sawmill: ['grass'],
    fisherman: ['water', 'grass'],
    grocery: ['grass'],
    foodcourt: ['grass'],
    well: ['grass'],
    windmill: ['grass'],
    fountain: ['grass'],
    house: ['grass'],
    inn: ['grass'],
    jousting: ['grass'],
    mansion: ['grass'],
    mayor: ['grass'],
    'streak-scroll': [],
    farm: ['grass'],
    lumber_mill: ['forest', 'grass'],
    market: ['grass', 'city', 'town'],
    cottage: ['grass'],
    crossroad: ['grass', 'city', 'town', 'crossroad', 'straightroad'],
    straightroad: ['grass', 'city', 'town', 'crossroad', 'straightroad'],
  };
  return defaultConnections[type] || [];
} 